<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street_InputStreet</name>
   <tag></tag>
   <elementGuidId>085d2aa6-a7c0-4a54-be87-91d84ca8c43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputStreet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputStreet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c051b3ed-f698-4142-b44d-e8edbbd14966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e89b9c1c-4fe2-4ed8-bacc-4b9a5c76f466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c77635e-2d8e-44f5-a79a-c8d1efb7db04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e22614ce-8fb1-4b36-877f-bde1931f0b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputStreet</value>
      <webElementGuid>b4d84e20-f4fc-408f-aa03-53c579c36306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputStreet&quot;)</value>
      <webElementGuid>374d7e32-b592-4fa3-a2e4-ae8ad88c72d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputStreet']</value>
      <webElementGuid>5e5f71d3-64ad-4b62-aaac-a398d345cf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b44-Column1']/div/span/input</value>
      <webElementGuid>6eabcd84-30ad-440d-8f46-cbb5f92afb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/input</value>
      <webElementGuid>4d8eb2eb-5ceb-42d3-9b29-ff0d28c2ac32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InputStreet']</value>
      <webElementGuid>b68c545f-fd8a-4d6c-9323-a4e6b88fbf77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
