<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_InputCity</name>
   <tag></tag>
   <elementGuidId>02b3d10a-03c1-4f52-ab4b-0a44cede3891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>727f2a0c-186d-4cb5-b226-c0ea4ec7d5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>858e5d6a-2156-41cd-871a-c59bb82eb53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>781508d8-0396-4e77-a109-baecab9ccda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>59c239bf-ae33-4b91-a463-b6e123cde034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputCity</value>
      <webElementGuid>9aae48ef-43f3-4d44-a73d-36559f4f2247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputCity&quot;)</value>
      <webElementGuid>c3f37aa3-e2f1-4189-a905-755afbbddb6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputCity']</value>
      <webElementGuid>90706994-2c26-456b-bfaa-c6489bbc3d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b44-Column3']/div/span/input</value>
      <webElementGuid>1cdc3b43-179d-4da7-90dd-47afe736caed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/span/input</value>
      <webElementGuid>be27a8a8-a23f-4879-866a-d2d86f605a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InputCity']</value>
      <webElementGuid>86fdf0b5-ba05-4c4c-96d7-a8cdebb47b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
