<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_Input_MN</name>
   <tag></tag>
   <elementGuidId>cc92cc4d-ef3c-4d1a-a955-474e1bf262ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_MN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_MN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51c038cb-b260-40bf-8ec9-651bdbce6353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>ff9ff54f-e016-44f7-a760-2303fb743078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c14dce5b-5089-48cf-9cf0-eb5a51e362b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>cf1e99d9-0688-415d-b822-b369f08a1ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_MN</value>
      <webElementGuid>b2b9d9bd-9a9f-4f8c-9b2a-de4d88210db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>916d7b88-10e4-4d5e-a24d-8ed3b307b175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>905 123 45</value>
      <webElementGuid>c9997cfb-b885-4505-900c-e91ada6ee2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad043933-8089-44d5-9ec6-f514a66b034c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_MN&quot;)</value>
      <webElementGuid>c3603042-3735-49d9-8d98-19ae94285ba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_MN']</value>
      <webElementGuid>d27c5885-bc91-452f-ba93-d3f075de0b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b42-Column1']/div/span/div/input</value>
      <webElementGuid>693db6cc-eb61-4c12-bc58-66a1e168dd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>595524c3-aaad-4baf-aa43-81a3a2a38946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_MN' and @placeholder = '905 123 45']</value>
      <webElementGuid>0835b962-ded9-476b-a906-636d48a473a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
