<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Place of Birth_InputDOB</name>
   <tag></tag>
   <elementGuidId>f619c3b2-784b-49cb-90e3-d1d2dd7cd575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputDOB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputDOB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87773a54-583c-4705-8eb1-bdd54de77544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>fcb27c59-ef2f-4fb0-a2b9-9f931f177c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bef0f404-7fb4-4762-902a-d660175f004d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>912567a3-432c-4b9d-ae2c-20609fd7850a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputDOB</value>
      <webElementGuid>02abfad7-7787-4345-a9ab-b72cd9d88548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputDOB&quot;)</value>
      <webElementGuid>39c4bfc1-13fe-4d38-a26e-433bd168408e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputDOB']</value>
      <webElementGuid>3ac2d3e7-1502-4b98-a6b5-42bd64198fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b42-Column2']/div/span/input</value>
      <webElementGuid>453a6a0e-1d58-43e9-9563-2dbd02ca7bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>5fb4afda-2b0c-49fa-85fe-0000886a51da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InputDOB']</value>
      <webElementGuid>50e59364-4f39-4691-9dcd-9539c347f8d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
