<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZipCode_InputZipcode</name>
   <tag></tag>
   <elementGuidId>30337a68-dc60-49d1-8394-e6428d175ee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputZipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputZipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39ae2b1b-b6e4-468a-b70d-c12586767ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>8783ced9-4bbc-48f6-8b72-e708d23e972e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c27883a-cb10-4108-965d-62661a590802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4b5d545f-3c3c-45f5-a97e-c1707a374f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputZipcode</value>
      <webElementGuid>be8699a0-584e-40ef-aa61-a1257454fe39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputZipcode&quot;)</value>
      <webElementGuid>8132e574-9a6a-45b0-bba4-7e50ba4df6e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputZipcode']</value>
      <webElementGuid>be9d9f3e-fbb5-4e3d-b26c-811b50c89304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b44-Column4']/div/span/input</value>
      <webElementGuid>67ebdfa7-df11-42cc-9b97-05b8d5248128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/span/input</value>
      <webElementGuid>a193b34b-bceb-4dff-ad34-eed8206ab67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InputZipcode']</value>
      <webElementGuid>d4ce0f4a-5b1a-47d9-b2ef-7521b110a628</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
