<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_InputAddress</name>
   <tag></tag>
   <elementGuidId>f838715e-0216-418b-b3a4-d2856224796c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa2d45f3-a25f-48ce-9f91-2be372fd90fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>4b10211a-7c34-4931-a4f6-e550a56f01b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>608b3554-9e81-4c1d-8461-9b3767f87d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>a1851869-9839-4a32-b687-11150700e6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputAddress</value>
      <webElementGuid>c9cf3428-6ee9-4cc1-8c1a-fe6c69478e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputAddress&quot;)</value>
      <webElementGuid>3f3f25b0-eb5c-474d-bc23-e90ec4b3c1eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputAddress']</value>
      <webElementGuid>3ac8fb77-d72f-4d39-9f3c-b704f804c3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b42-Column3']/div/span/input</value>
      <webElementGuid>40430798-ed60-424f-a288-b5dbb6882929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/input</value>
      <webElementGuid>0ee76452-6f6c-4022-90f5-c4c5a4af4364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'InputAddress']</value>
      <webElementGuid>2847e234-03fc-4db6-a06b-4c4cb53ea67b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
