<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Province_InputProvince</name>
   <tag></tag>
   <elementGuidId>b38b92c1-92ac-404e-b07e-0f50ff4e2063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputProvince</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputProvince']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3ffd81d-671e-4a4d-9ff8-f73479ca6b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>fc2aa794-7805-4b71-910b-e655ccab7779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed9ab2b8-113a-4b81-b21e-ace773ceb103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>2a74f40b-b1aa-46e9-ab4c-c8faed754d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputProvince</value>
      <webElementGuid>b6de0081-b1a5-4258-b656-363397223875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputProvince&quot;)</value>
      <webElementGuid>ec5b5555-39aa-42de-9252-4e6f5db20e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputProvince']</value>
      <webElementGuid>1dce0d36-b228-4318-9541-f8a32e58754c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b44-Column5']/div/span/input</value>
      <webElementGuid>2abea92e-9606-4559-86cf-86f581dd89a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/input</value>
      <webElementGuid>11d3468d-47be-4b3a-b5d4-b3d8015316e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InputProvince']</value>
      <webElementGuid>14f7b921-2dc5-43a1-9a3d-70f87c8ad5b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
