<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Barangay_InputBrangay</name>
   <tag></tag>
   <elementGuidId>157e9dbc-06d6-4a97-9278-c5177db07d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputBrangay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputBrangay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97457bdd-99d4-44bc-8fc6-4c7e4ff2a539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>c0168612-a19a-43ed-9d04-9e40fd8eb858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2474dcb-c18f-4901-a7b4-73db9009a0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6cd91719-0625-41b2-a52f-e6ddca4c4b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputBrangay</value>
      <webElementGuid>97c4b65b-8a03-4ee9-ab9c-24e32349366c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputBrangay&quot;)</value>
      <webElementGuid>e2e4f1bc-45b9-414a-b164-633cdb6d0377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputBrangay']</value>
      <webElementGuid>3db874f0-0255-4d5f-be78-1543bf41bfda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b44-Column2']/div/span/input</value>
      <webElementGuid>518f176f-2944-4e2a-843c-6b74c80927c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/span/input</value>
      <webElementGuid>6c0e8b77-9239-4c8d-8fce-ec14de5720ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InputBrangay']</value>
      <webElementGuid>ab2c39e6-01d2-4ca2-a76d-2ad8d4164320</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
