<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TIN Number_FinalstepAccountNumber2</name>
   <tag></tag>
   <elementGuidId>12c52440-990b-4495-9ecb-66921188542b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FinalstepAccountNumber2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FinalstepAccountNumber2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bfccf0c-5f1a-4b2e-8037-6b770e4553bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>f57b16a5-e724-4804-bc61-f0a33cbf6f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e44f6005-a991-45f5-a6b2-d9b48b91fb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7dcfb5d4-d402-4aa6-acbd-4aa074130666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FinalstepAccountNumber2</value>
      <webElementGuid>a928c9cb-2d1b-4216-8082-06f0e37d8119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FinalstepAccountNumber2&quot;)</value>
      <webElementGuid>8105bc79-c57d-4271-87a5-1bfa640705a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FinalstepAccountNumber2']</value>
      <webElementGuid>9d031546-16ea-4c11-9d80-3de6c46e35fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b50-Column3']/div/span/input</value>
      <webElementGuid>3da552fa-e031-4c5e-a06b-486b200e13a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/input</value>
      <webElementGuid>f0f1fde1-6ddc-4dcd-91c0-c59f49a4d7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FinalstepAccountNumber2']</value>
      <webElementGuid>e826d28d-848c-429d-86b7-4a9e77507d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
