<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Immediate Address_ImmediateContactNumber (final11)</name>
   <tag></tag>
   <elementGuidId>51e6ed70-7518-4db0-9460-24c3ba00e8b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ImmediateContactNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ImmediateContactNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fc4bf27-e14d-4797-853c-0cf1d0c6c916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>4bbae212-ce64-411e-a8f4-c8452f0c4e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78d76be7-82c4-450b-9d31-ea52db090587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ImmediateContactNumber</value>
      <webElementGuid>1248fff9-6759-4ae0-a395-39fda0cef9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ImmediateContactNumber&quot;)</value>
      <webElementGuid>ea9ca811-863a-45b1-b0b3-088ca6da092c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ImmediateContactNumber']</value>
      <webElementGuid>be8e8f9d-36dc-412d-bafa-f87e7a68c0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b47-Column2']/div/span/input</value>
      <webElementGuid>04e37933-20e1-4cde-b98e-1d780f51cd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>988dde36-e0f6-4291-8dee-ce1e8ea1415f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ImmediateContactNumber']</value>
      <webElementGuid>61726019-38a5-4229-ac66-a85d6d89c50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
