<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create New Stockholder_submenu-2-icon</name>
   <tag></tag>
   <elementGuidId>091c9a1b-3728-4fee-9225-e9c814ec3ae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.submenu-2-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b4-TitleContainer']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5c54207-3f63-4cfd-862b-d65a54b0c534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-2-icon</value>
      <webElementGuid>477ab3ef-a920-4e99-aa39-ca3cfeec731f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-TitleContainer&quot;)/div[@class=&quot;submenu-2-icon&quot;]</value>
      <webElementGuid>1feffdbf-2242-44c9-84b0-156a893f363b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-TitleContainer']/div[2]</value>
      <webElementGuid>43d86a9b-3d8f-48e4-bdf8-74384a3290c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>c51c6226-6528-4abc-9c99-3903e5b38090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
