<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Individual ShareholderCorp_3d3b64</name>
   <tag></tag>
   <elementGuidId>4afe69ef-effb-4cc5-9d76-03445b830116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6b0a2f74-63ed-483f-9399-4f25fcb9cee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>ae7ef30b-1d31-4091-a161-c807409a3114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d19ed5e0-8a15-4f0f-a408-764aeb709be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown8</value>
      <webElementGuid>5e717fd4-1f79-4395-b3af-7863c94f4ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Individual ShareholderCorporate Shareholder</value>
      <webElementGuid>cd9fc111-89af-4d93-8e29-899220803627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown8&quot;)</value>
      <webElementGuid>b9961dd8-4ce3-47aa-af76-9943d8529a9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown8']</value>
      <webElementGuid>ae1aed24-463d-4217-9ce9-e54ecbc9610c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown8-container']/select</value>
      <webElementGuid>0b1496ed-4bd9-4e56-8e3a-9cdb3cda3f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholder Type'])[1]/following::select[1]</value>
      <webElementGuid>bb949c65-1b63-48bd-819e-df3b1605f9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution'])[1]/following::select[2]</value>
      <webElementGuid>f5afdd94-b172-4914-beff-7865ebf7af6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Status'])[1]/preceding::select[1]</value>
      <webElementGuid>b4b6687f-24f2-413e-986b-2beb4be0bfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Record:'])[1]/preceding::select[2]</value>
      <webElementGuid>88a125de-a418-4588-9edb-082bee6d9082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>b6304f5a-2fab-44f0-b865-bc3b99b2056d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown8' and (text() = '--Select--Individual ShareholderCorporate Shareholder' or . = '--Select--Individual ShareholderCorporate Shareholder')]</value>
      <webElementGuid>a711b688-2507-41d4-90c1-1064e1163682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
