<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date Aquisition_Input_DateAquisition</name>
   <tag></tag>
   <elementGuidId>b48d251b-4e38-42c4-be9e-179cdf8486d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_DateAquisition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_DateAquisition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>673d9249-5d41-496c-b1ae-8069625de22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>6703224c-1187-47db-a6c7-fff60435a5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>694fb819-2e47-47d0-998d-233723a7369f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_DateAquisition</value>
      <webElementGuid>cd66c65f-be36-437c-92c4-65e4dc0da087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_DateAquisition&quot;)</value>
      <webElementGuid>f86d9cfc-fb81-4077-a0c5-500514e605b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_DateAquisition']</value>
      <webElementGuid>6a370a33-5106-4bf8-ba5c-fd3a31ea67b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b10-Column4']/div/span/input</value>
      <webElementGuid>5221720f-2aad-49da-88d8-cabbf4f24d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/input</value>
      <webElementGuid>e89fafb5-51d8-4e87-8c49-95486e49f652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'Input_DateAquisition']</value>
      <webElementGuid>f5d62997-9e7b-459e-91a2-6e92f64cca89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
