<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ProfileAdd New</name>
   <tag></tag>
   <elementGuidId>c0107aef-6492-4014-b37e-c6cdacc63c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-$b5']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b525b130-8498-496f-8296-65f27ab9dad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-2</value>
      <webElementGuid>829840eb-b2c1-4044-873a-4bef065e7428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProfileAdd New</value>
      <webElementGuid>ecabca51-080c-406b-9e8e-2defd4e4594f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-$b5&quot;)/div[@class=&quot;submenu-2&quot;]</value>
      <webElementGuid>47fce9da-d213-4390-b81f-56b70f986f1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-$b5']/div</value>
      <webElementGuid>93eb9a66-3b3d-45c3-8c09-c91e0f1f9109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Stockholder'])[1]/following::div[4]</value>
      <webElementGuid>fe182f97-41d7-4746-9668-ebe386e2656b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholder Information'])[1]/following::div[10]</value>
      <webElementGuid>4b219c25-1727-4167-9340-554fae6ba055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>ced38ada-104b-47cb-ab30-aa97634d4158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ProfileAdd New' or . = 'ProfileAdd New')]</value>
      <webElementGuid>07f2de64-adcf-4abb-8def-6f12d6154bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
