<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Profile_submenu-2-icon</name>
   <tag></tag>
   <elementGuidId>f0eca6e1-2bf7-442f-b290-35fcfea50afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b5-TitleContainer > div.submenu-2-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b5-TitleContainer']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>216c2746-590e-4cff-b69a-a8c0c89f6b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-2-icon</value>
      <webElementGuid>5858f566-6d73-47e5-aef4-7fd06d52c210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b5-TitleContainer&quot;)/div[@class=&quot;submenu-2-icon&quot;]</value>
      <webElementGuid>c1b79b74-45bf-4776-aace-4aec4e9fbe4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b5-TitleContainer']/div[2]</value>
      <webElementGuid>ae3e6ba5-10dc-4290-b776-e36a4107a1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>92d14653-ee54-4b82-bb93-f902c00e26bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
