<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Action_icon fa fa-chevron-down fa-1x</name>
   <tag></tag>
   <elementGuidId>193300fd-a5e1-4990-b365-ecf4ae5a450f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-chevron-down.fa-1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l7_0-77_0-b18-IconOpen']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>92816694-aef3-494e-af16-d381e82c833e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-chevron-down fa-1x</value>
      <webElementGuid>45afe576-e64f-42ca-abf0-753b6f4579a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l7_0-77_0-b18-IconOpen&quot;)/i[@class=&quot;icon fa fa-chevron-down fa-1x&quot;]</value>
      <webElementGuid>7520f691-ecb1-4372-b65f-474d06172a30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l7_0-77_0-b18-IconOpen']/i</value>
      <webElementGuid>35f54482-a3af-4079-89e6-0412c8941342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
      <webElementGuid>72936c17-a8ea-40a6-979c-edb674bdb87b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
