<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Staff Id No_Input_StaffId2</name>
   <tag></tag>
   <elementGuidId>2241902b-7881-48a5-9aba-1bdc6b76c680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_StaffId2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_StaffId2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b66c21c-fe16-49b8-b0ee-6313202958a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>2964e7d0-99f3-44e0-9e43-8cf94884ce01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a12bd793-9f0d-4499-b03f-c8b94e10dcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fb330204-0431-43f1-ba97-d6887a7cc54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_StaffId2</value>
      <webElementGuid>89b9df31-038b-4e64-9f65-b3a1daa90036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_StaffId2&quot;)</value>
      <webElementGuid>3835f940-b981-44d7-a16c-cb244423ca44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_StaffId2']</value>
      <webElementGuid>1d24dd0b-3b7a-409a-9cc1-f4e8c75d72cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form1']/div/div[6]/span/input</value>
      <webElementGuid>93bd24df-41b4-4800-b06b-4c9db3e29c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/input</value>
      <webElementGuid>ef759863-d312-4677-969f-1abd76a2722b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_StaffId2']</value>
      <webElementGuid>d4eb8763-727d-4ecc-b3e3-4ecf46f74de8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
