<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone_MobileNumber</name>
   <tag></tag>
   <elementGuidId>e2f201df-373b-40f1-807c-0a610aa8c8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39e40a2d-4c6c-4d90-a74c-eae13c52babc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e83d6e6b-d19e-454e-9f2e-15b66387e6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>449dbf62-f40a-4e1b-b4f2-d7f63c70bc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>7f222c60-a2ce-45be-9110-61c9071206e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MobileNumber</value>
      <webElementGuid>65c349d4-76b1-4dc5-a960-f14a7f319e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MobileNumber&quot;)</value>
      <webElementGuid>1e501eef-dd50-43cb-880a-7ec160f18ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MobileNumber']</value>
      <webElementGuid>701385de-48a4-476a-9bde-89390907b02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NameMnameLName']/span[4]/input</value>
      <webElementGuid>d6f7822a-6270-4986-8e00-a884969a9287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/input</value>
      <webElementGuid>c0d5fe85-786b-4d3b-9276-bb1b86fca6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'MobileNumber']</value>
      <webElementGuid>0b9bea34-f564-40fb-a53f-d9f5acc1c13f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
