<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AGRIBANKBankAdminBatangas _a0a28e</name>
   <tag></tag>
   <elementGuidId>6141cd07-44a9-4430-869b-bdac044c9287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c47bd8fc-69e4-4ed0-8ce7-809055b6c478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>d887b45e-f155-4885-8282-8da90990fd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2a5776d1-c9b1-41d3-861b-037b9cdd4adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown5</value>
      <webElementGuid>115c3794-ebad-4b96-ae30-8bb1fe70a082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AGRIBANKBank/AdminBatangas City 1Batangas city 2ABatangas City 3ABatangas City 3BBATANGAS CITY 4BATANGAS CITY 5Batangas City 6Batangas city 8BAUAN 1ABAUAN 1BBauan 1C-QSLBauan 2LoboLobo2MABININo-NameQsl BatangasSAN PASCUAL 1SAN PASCUAL 2SME UnitSME Unit 2Taysan</value>
      <webElementGuid>bd06f949-7039-4df7-b7ea-dae4a6be221c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown5&quot;)</value>
      <webElementGuid>fdeede6a-af2f-491a-b705-5efbed3fabdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown5']</value>
      <webElementGuid>1c966dec-cca2-48fd-b93b-dab359ba49c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown5-container']/select</value>
      <webElementGuid>4da5efaa-aff7-47a8-85b6-3a6715cfc4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::select[2]</value>
      <webElementGuid>1994a6b0-c391-46e4-b8f8-99c375acd7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>d2e541d3-40be-4e2a-b12a-8dd71b71047e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown5' and (text() = '--Select--AGRIBANKBank/AdminBatangas City 1Batangas city 2ABatangas City 3ABatangas City 3BBATANGAS CITY 4BATANGAS CITY 5Batangas City 6Batangas city 8BAUAN 1ABAUAN 1BBauan 1C-QSLBauan 2LoboLobo2MABININo-NameQsl BatangasSAN PASCUAL 1SAN PASCUAL 2SME UnitSME Unit 2Taysan' or . = '--Select--AGRIBANKBank/AdminBatangas City 1Batangas city 2ABatangas City 3ABatangas City 3BBATANGAS CITY 4BATANGAS CITY 5Batangas City 6Batangas city 8BAUAN 1ABAUAN 1BBauan 1C-QSLBauan 2LoboLobo2MABININo-NameQsl BatangasSAN PASCUAL 1SAN PASCUAL 2SME UnitSME Unit 2Taysan')]</value>
      <webElementGuid>7b26dc45-27db-4ddd-b1d5-7f9770a26633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
