<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--CARD Bank, Inc.CARD SME Ba_231bc7</name>
   <tag></tag>
   <elementGuidId>74c81b15-e12b-4d45-8185-f82a322ee488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f02ab272-89c8-4a12-a1f4-22fc0f6c27e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>62d743ee-76a8-471c-948f-7d47f8d13696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35734846-2170-4234-918e-cf212891a64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown2</value>
      <webElementGuid>0625e36a-066e-4b62-808c-52b9db1504d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--CARD Bank, Inc.CARD SME Bank Inc.CARD MRI Rizal Bank Inc.CARD Inc.</value>
      <webElementGuid>fbcffa6d-0c29-4568-9429-839e73fb1f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown2&quot;)</value>
      <webElementGuid>7411b3d6-f0ca-45ce-a069-dd27e88c70e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown2']</value>
      <webElementGuid>a950b65e-2f9c-4e46-8486-8752c5f3ebdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown2-container']/select</value>
      <webElementGuid>abc77b5d-4250-47db-ad16-0a37317fce0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned Office'])[1]/following::select[1]</value>
      <webElementGuid>e921fcd9-11f5-402f-9050-118e0475a57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/select</value>
      <webElementGuid>1e0f32e2-b2e8-46a5-85f2-a7c2a49cfc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown2' and (text() = '--Select--CARD Bank, Inc.CARD SME Bank Inc.CARD MRI Rizal Bank Inc.CARD Inc.' or . = '--Select--CARD Bank, Inc.CARD SME Bank Inc.CARD MRI Rizal Bank Inc.CARD Inc.')]</value>
      <webElementGuid>42e96825-15bb-4a84-bef7-516155179a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
