<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Area ManagerBook KeeperSto_e31272</name>
   <tag></tag>
   <elementGuidId>7d733175-47b8-4aa8-917d-c29723983a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1b5234e9-c55f-495a-9ce3-8ddf96ede0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>a87de4ff-0d8c-4c53-8634-e30d2f2255f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11943015-93a1-4fc9-b583-048ab3dfb80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown6</value>
      <webElementGuid>3651d052-3a46-4403-b95d-1ca38e956715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Area ManagerBook KeeperStock AdminSec AdminApp AdminComplianceFinanceRisk</value>
      <webElementGuid>73a82723-b0a5-4893-a66e-4df04e048a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown6&quot;)</value>
      <webElementGuid>2061e0d5-13a4-4b25-a4b1-f452d69f54fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown6']</value>
      <webElementGuid>a36264a8-9b6a-428b-a11d-dd5d536a7c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown6-container']/select</value>
      <webElementGuid>63335295-1894-48da-bc30-22966dc62a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::select[1]</value>
      <webElementGuid>911caf97-4e0d-4c83-8154-19a8e8cc2b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>97ea6a34-48b7-45f5-b385-e0c5fd7fff2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>7577f01c-10b2-473d-bda4-b3d68f71e4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown6' and (text() = '--Select--Area ManagerBook KeeperStock AdminSec AdminApp AdminComplianceFinanceRisk' or . = '--Select--Area ManagerBook KeeperStock AdminSec AdminApp AdminComplianceFinanceRisk')]</value>
      <webElementGuid>c61f4496-8610-4b3d-b278-b58523a82025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
