<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Sto. TomasLemeryBatangasRo_dd9050</name>
   <tag></tag>
   <elementGuidId>09fb1113-5b88-477b-b2cb-17e7dfb92edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6279e818-6fad-4672-89a2-ae524eab13c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>f92c501d-d360-41a8-9720-8df6b86fe568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c00aee89-07fc-4471-a396-b25a9d4e9e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown4</value>
      <webElementGuid>3a36bf31-795a-49b4-acbb-2816a94c00b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Sto. TomasLemeryBatangasRosarioLipa BranchBalayanNasugbuTanauan</value>
      <webElementGuid>f6f1fac6-bdc8-43d1-9624-237b9ce838c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown4&quot;)</value>
      <webElementGuid>269c206d-c1c5-4f5e-a1d8-32ae6013548e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown4']</value>
      <webElementGuid>02333012-5cdd-49b9-810c-7966cf326dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown4-container']/select</value>
      <webElementGuid>66df5c3f-92b4-44fd-ad6c-dfa2ccce1e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>857ba505-6008-4731-a214-2f9dacb8ab1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown4' and (text() = '--Select--Sto. TomasLemeryBatangasRosarioLipa BranchBalayanNasugbuTanauan' or . = '--Select--Sto. TomasLemeryBatangasRosarioLipa BranchBalayanNasugbuTanauan')]</value>
      <webElementGuid>fa5d5fe9-4850-4f99-9748-477c65bc9278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
