<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PDF_b10-LayoutPrint</name>
   <tag></tag>
   <elementGuidId>f6db9f5c-e789-4903-bdde-268e4567aa01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b10-LayoutPrint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b10-LayoutPrint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac76a5b4-2dd8-4e7b-b947-69234f864200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout-print</value>
      <webElementGuid>60a20b70-d13c-4438-9557-106eb4ca5518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-layout-print-hide-first-header</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a958f9c7-bfc5-4b3d-bcf3-a8dafb596eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-layout-print-hide-last-footer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d877e2f1-ca0d-446f-a9ea-aacbfe17e285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b10-LayoutPrint</value>
      <webElementGuid>73995ef0-284b-4f2d-b35d-30db38d1e118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b10-LayoutPrint&quot;)</value>
      <webElementGuid>06ef3973-5268-42ed-97e9-14eedc626775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b10-LayoutPrint']</value>
      <webElementGuid>fd01ec24-8b62-4a26-9ff0-e487675f99e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b10']/div</value>
      <webElementGuid>40b0beb3-bc5a-459e-a132-8334f7787d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/following::div[7]</value>
      <webElementGuid>98096ef4-d45d-462c-982c-d13a819a74bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b10-LayoutPrint', '&quot;', ')')])[1]/preceding::div[7]</value>
      <webElementGuid>c1587333-1697-4ee8-946c-07f0f053eb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::div[9]</value>
      <webElementGuid>63699ed0-1c46-4142-9ca1-e783ca5112bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>b433de1e-bc8e-4b07-b808-445a6a6734d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b10-LayoutPrint']</value>
      <webElementGuid>9fa99248-97c3-472a-95f3-e56b716e3a5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
