<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Generation Header1</name>
   <tag></tag>
   <elementGuidId>57c8f7f5-a332-4ce8-948f-7db0ebc8c431</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-Content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b1-Content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ec4d5ab-5709-4399-95bb-379370896e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout-print-hide</value>
      <webElementGuid>cf6c8202-95ba-40fa-b5fa-f64a913ee6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-Content</value>
      <webElementGuid>1245e3e8-bf6e-4570-8499-f3dca6af34a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generation Type --Select Type--Per InstitutionPer BranchIndividualInstitutionBranchStart Date:End Date:Generate Print / PDF</value>
      <webElementGuid>bef7e8a6-f265-4fee-a17b-203b23406213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-Content&quot;)</value>
      <webElementGuid>ab709703-0342-45ea-acd1-3e8c10d483d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b1-Content']</value>
      <webElementGuid>5730db65-34d8-43a5-b450-d6a5b3369281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b1']/div</value>
      <webElementGuid>802e405d-ae47-45a5-b96c-49f16e38ed00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>59b594b7-e2a5-4310-b5e3-bc53ba14649d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b1-Content' and (text() = 'Generation Type --Select Type--Per InstitutionPer BranchIndividualInstitutionBranchStart Date:End Date:Generate Print / PDF' or . = 'Generation Type --Select Type--Per InstitutionPer BranchIndividualInstitutionBranchStart Date:End Date:Generate Print / PDF')]</value>
      <webElementGuid>3f3f69f4-e846-41ba-8a3d-c77a17c50f72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
