<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Action_icon fa fa-chevron-up fa-1x</name>
   <tag></tag>
   <elementGuidId>3f80095d-7aaf-42e2-b8cc-1ff500579900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-chevron-up.fa-1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l7_0-77_0-b18-IconClose']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3e596faf-684a-479c-a66b-d65b210dded2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-chevron-up fa-1x</value>
      <webElementGuid>943c8f18-0973-400b-8822-cf2b86d3ff37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l7_0-77_0-b18-IconClose&quot;)/i[@class=&quot;icon fa fa-chevron-up fa-1x&quot;]</value>
      <webElementGuid>f4b07bf2-a5e0-4eaf-b734-06afd815dfc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l7_0-77_0-b18-IconClose']/i</value>
      <webElementGuid>2e4d3a04-3a14-4329-8789-22c4473ae798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
      <webElementGuid>cf41e09d-cd87-4aac-ae5a-c88e1a181c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
