<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_Input_StaffId</name>
   <tag></tag>
   <elementGuidId>cce60aae-8fda-4b9e-9f4e-b2bcc3bb31c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_StaffId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_StaffId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ebb7725-4b35-4e6b-9c42-e07a67583dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e3e63b54-dd43-48fd-898e-557db45739f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>b0aa8769-2a10-4b14-9989-107bfc4b071e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_StaffId</value>
      <webElementGuid>60bce8cd-087d-422a-ba06-35160cf55633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_StaffId&quot;)</value>
      <webElementGuid>acdf8364-df07-4039-ab6b-fb08c5d5446f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_StaffId']</value>
      <webElementGuid>abbc76d7-9d33-4407-bf53-9dc7f1231ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form1']/div/div[5]/span[2]/input</value>
      <webElementGuid>7bfce6b7-b3a9-454e-92d2-7434017604fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>f379b115-9785-4d41-b7ca-f4c0257bc46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'datetime-local' and @id = 'Input_StaffId']</value>
      <webElementGuid>4f61f6dc-fae7-4e81-8b55-a1eed59af096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
