<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Close_vscomp-search-input</name>
   <tag></tag>
   <elementGuidId>1ba958b0-5001-4f3e-9501-56da7ceb4b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.vscomp-search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>feec0b50-68b2-4d76-8740-94bfbdc58e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9407b472-66e2-49b0-a7b5-0ffd7a26e603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-search-input</value>
      <webElementGuid>5d982e9c-e53a-442d-bf9f-20aeda51c7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>8eaeaa36-beae-4461-8b8b-cb3fef5dcc31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-dropbox-container-8470&quot;)/div[@class=&quot;vscomp-dropbox&quot;]/div[@class=&quot;vscomp-search-wrapper&quot;]/div[@class=&quot;vscomp-search-container&quot;]/input[@class=&quot;vscomp-search-input&quot;]</value>
      <webElementGuid>f4da4a3a-52f4-47b4-a774-730b40fc71be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>23a832c2-8bdf-4a71-aa5f-8f7b56ffccb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-dropbox-container-8470']/div/div/div/input</value>
      <webElementGuid>52c8f557-90ab-4fcc-a81c-cf106ec760b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>4a839889-a7f7-4a9b-8dc4-448b259d7977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search...']</value>
      <webElementGuid>51af1af1-a4be-45e6-805f-cc22abc7b6e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
