<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--MemberNonMemberStaff</name>
   <tag></tag>
   <elementGuidId>bed51ffa-012e-4ae4-ac46-3b267448d486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownClientType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownClientType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>52c7bbea-764f-437b-93ac-6e241332e6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>6e6cc845-4eac-465f-af71-dad1ef22bb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9791e858-7052-4421-bd53-9a1619df84f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownClientType</value>
      <webElementGuid>f6ea4177-f52d-40e2-bb57-a72157b4b953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--MemberNonMemberStaff</value>
      <webElementGuid>2f121970-3837-4f16-88a2-9503068b9afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownClientType&quot;)</value>
      <webElementGuid>bd1f1c6f-e353-438a-a03a-8952a423e2b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownClientType']</value>
      <webElementGuid>4e6140bb-f756-4034-9a83-272f68e097bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownClientType-container']/select</value>
      <webElementGuid>a52dee1e-2e24-4a69-87a5-9fe39a25a216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Types'])[1]/following::select[1]</value>
      <webElementGuid>d3be9cd0-4d2b-48b8-bc43-b069dfc0818b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/following::select[1]</value>
      <webElementGuid>f6b62619-906c-4ec1-9e22-51718d02931e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Stockholder'])[1]/preceding::select[1]</value>
      <webElementGuid>bc379c05-613e-4819-80d8-d7c1ba92bb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tagkawayan 123232-13131'])[1]/preceding::select[2]</value>
      <webElementGuid>79d4ff6c-bab9-42c7-a34f-0ff5cf93e6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9a30e3f0-3f57-440c-8bef-a4e4c5dc6a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownClientType' and (text() = '--Select--MemberNonMemberStaff' or . = '--Select--MemberNonMemberStaff')]</value>
      <webElementGuid>92325f55-bed6-4a6f-b52d-ac609a9a8f16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
