<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Individual ShareholderCorp_3d3b64</name>
   <tag></tag>
   <elementGuidId>b7853c16-9842-48e8-9887-d80259d39c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownStockholderType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownStockholderType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>babf3b62-5d9d-4eff-a0cd-deda413a4550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>0b38f152-d619-4328-a35d-117c2094e2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df8e52c6-5e8e-4c92-b46e-cafbc4921e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownStockholderType</value>
      <webElementGuid>e02cf312-05ce-4414-acdf-6ac61d7238e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Individual ShareholderCorporate Shareholder</value>
      <webElementGuid>38e28e93-56f6-488f-939d-510e2db0cfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownStockholderType&quot;)</value>
      <webElementGuid>91f923ff-8652-4566-8c4f-4893f457fd8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownStockholderType']</value>
      <webElementGuid>b3569673-d037-4804-8fe1-62a7acd8515d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownStockholderType-container']/select</value>
      <webElementGuid>b0ca2c77-5a00-44de-81ae-4ca1cc323c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Stockholder'])[1]/following::select[1]</value>
      <webElementGuid>fabf5fa4-b2c6-4142-b09c-ed1dbb1ac0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Types'])[1]/following::select[2]</value>
      <webElementGuid>b7613a83-3452-4a91-9f43-8d1fd41a47c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tagkawayan 123232-13131'])[1]/preceding::select[1]</value>
      <webElementGuid>1336de64-80d4-4cb2-b322-375e1c893f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Admin'])[1]/preceding::select[1]</value>
      <webElementGuid>0f9c2a99-090b-4608-a239-a77afaf88241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>5abc23ff-dc0c-4392-9098-4b3acc5cd26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownStockholderType' and (text() = '--Select--Individual ShareholderCorporate Shareholder' or . = '--Select--Individual ShareholderCorporate Shareholder')]</value>
      <webElementGuid>bdfafcb8-93a7-46a1-9a3d-28197e95c836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
