<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--CARD Bank, Inc.CARD SME Ba_231bc7</name>
   <tag></tag>
   <elementGuidId>c345db48-8097-4910-83fc-3cac0353a7dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownInstitution</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownInstitution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d15733b-d14e-455e-80f6-e0a85f3d8827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>f217afa9-8c77-453f-8b41-3a9de7115c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ca48f11e-56b9-47db-9109-0fcf4d52c670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownInstitution</value>
      <webElementGuid>db4ea7e6-9e4e-4c85-91e1-0b9a0fc2bfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--CARD Bank, Inc.CARD SME Bank Inc.CARD MRI Rizal Bank Inc.CARD Inc.</value>
      <webElementGuid>6e91b62a-55cd-46d8-a418-9532b77a766a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownInstitution&quot;)</value>
      <webElementGuid>be483b6b-a489-4aa6-a57a-8000126e9074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownInstitution']</value>
      <webElementGuid>f0dac6dd-112c-4424-977d-a5db5681afde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownInstitution-container']/select</value>
      <webElementGuid>9f8b1196-ce3f-4a53-89c5-6ce9420d879b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution'])[1]/following::select[1]</value>
      <webElementGuid>f01d51d5-409c-4286-89a8-a13c976e717d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholder'])[1]/following::select[1]</value>
      <webElementGuid>45d45d0a-d458-4f85-8dc5-b20e5108bb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[1]/preceding::select[1]</value>
      <webElementGuid>5b69ee6d-79fc-4ee3-bc2e-599f5b50caf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/preceding::select[1]</value>
      <webElementGuid>2366b1a3-d84e-4c57-a12b-c0bea5fb975e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/select</value>
      <webElementGuid>7cef1719-13ae-4b6c-a059-956b925068d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownInstitution' and (text() = '--Select--CARD Bank, Inc.CARD SME Bank Inc.CARD MRI Rizal Bank Inc.CARD Inc.' or . = '--Select--CARD Bank, Inc.CARD SME Bank Inc.CARD MRI Rizal Bank Inc.CARD Inc.')]</value>
      <webElementGuid>78986b78-0e2a-429d-aac0-f46951e97d27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
