<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AKAP 1</name>
   <tag></tag>
   <elementGuidId>2e46bc29-b2c8-45fe-bee7-8f97becbc7d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-1011-0 > span.vscomp-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-1011-0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>800476bf-d786-45d5-b438-d2ebe5a59556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-option-text</value>
      <webElementGuid>1a5c4ba2-9ffe-4b03-b236-e21c7177649a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>AKAP 1</value>
      <webElementGuid>9fa9137b-b858-4173-af56-3ee0d6f86623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-enter-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>1c382600-b23a-4fa1-925e-22de17b3d852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-z-index</name>
      <type>Main</type>
      <value>251</value>
      <webElementGuid>5d2118ec-fda4-4227-80bd-8d6d132af8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-font-size</name>
      <type>Main</type>
      <value>14px</value>
      <webElementGuid>c2ff5252-78d0-43df-ba36-9fc6d33537c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-alignment</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>2677d5fc-601a-46a4-8ace-465aa4084d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-max-width</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>5604db58-e880-49a6-acf2-2ec9df627e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-ellipsis-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>05c1b907-4df5-475e-87f0-41fa1c512feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-allow-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2fd05983-80e7-4f94-8b77-d35529cefaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            AKAP 1
          </value>
      <webElementGuid>ecc6119c-6a51-49d6-a080-b3dda6d7e643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-1011-0&quot;)/span[@class=&quot;vscomp-option-text&quot;]</value>
      <webElementGuid>eb26c04e-dd9b-4632-9965-1f6099271673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-1011-0']/span</value>
      <webElementGuid>3b258e51-f38c-449c-bbd9-af401ee05827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::span[1]</value>
      <webElementGuid>0ffb595a-3228-4a69-9252-1720d7a9aa40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no options to show.'])[6]/following::span[3]</value>
      <webElementGuid>e657442d-c762-4a47-99c6-e48047e545de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKAP 1 ( MAAGAP )'])[1]/preceding::span[1]</value>
      <webElementGuid>6b649b95-67f4-47f5-ad2f-cdfe1b2823f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKAP 1 SPC'])[1]/preceding::span[2]</value>
      <webElementGuid>0fd3fc43-4e68-48a4-9e0e-87bd8ca2e9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AKAP 1']/parent::*</value>
      <webElementGuid>25849082-ba69-4884-9d1c-6f50a71ad246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div[2]/div/div/span</value>
      <webElementGuid>066199ad-b183-45e9-a4e9-df6d56019406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            AKAP 1
          ' or . = '
            AKAP 1
          ')]</value>
      <webElementGuid>b92babcb-39ab-4893-9fc5-873fc85d58f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
