<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SPC 2</name>
   <tag></tag>
   <elementGuidId>eedd75f2-c23d-4deb-b347-8ac3439015a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-9378-2 > span.vscomp-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-9378-2']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c6e5c89-e26a-41a9-8212-513ac6e67b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-option-text</value>
      <webElementGuid>3103ddcb-bdd8-4735-bb1e-de1e7dd5ffa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>SPC 2</value>
      <webElementGuid>abeb49d3-b4b3-4855-b947-1b371f273015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-enter-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>146e30dd-7afd-4f12-92e0-9830dcb16eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-z-index</name>
      <type>Main</type>
      <value>251</value>
      <webElementGuid>235067d1-1cb3-485c-9a63-a0f391101826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-font-size</name>
      <type>Main</type>
      <value>14px</value>
      <webElementGuid>a55cd09e-398f-460a-8d10-e22d666fa4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-alignment</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>b17b8131-56e7-4650-866e-f0531124d288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-max-width</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>d180d007-173d-4cad-90aa-d3d931976b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-ellipsis-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44916dda-04b5-4b13-aa0c-3e2fc0e4e90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-allow-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c673e4a5-50b5-4b65-96e5-2553ccfa0dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            SPC 2
          </value>
      <webElementGuid>a211d678-0a56-46d4-9499-c5b490a6a73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-9378-2&quot;)/span[@class=&quot;vscomp-option-text&quot;]</value>
      <webElementGuid>18864d81-dd04-482b-9cc5-0c1fdd7361e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-9378-2']/span</value>
      <webElementGuid>6153b52b-a7bf-4903-b00e-2bc04985a47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPC 11'])[1]/following::span[1]</value>
      <webElementGuid>c3b6c60a-6f4e-4a2b-9b46-cbcba2ca5ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barleta Default Unit'])[1]/following::span[2]</value>
      <webElementGuid>730214e5-531d-4817-985e-ba60099ce89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPC 3'])[1]/preceding::span[1]</value>
      <webElementGuid>a32e525e-fb97-4d71-9feb-2cab23ee8096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPC 4'])[1]/preceding::span[2]</value>
      <webElementGuid>54040fa5-602a-46a1-996f-880f39bb6c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SPC 2']/parent::*</value>
      <webElementGuid>15478b60-6bf8-4fae-849d-4f1414cd3886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div[2]/div/div[3]/span</value>
      <webElementGuid>28265ec4-f836-488e-b95e-f9d0a27682dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            SPC 2
          ' or . = '
            SPC 2
          ')]</value>
      <webElementGuid>2ae47b15-1f10-45df-b648-ddaeeda017c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
