<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_REGION 4-A</name>
   <tag></tag>
   <elementGuidId>5896a425-3353-4d29-9d9a-d3d8a97566fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-970-2 > span.vscomp-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-970-2']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5fa7745c-5248-400d-8835-94a3a622669e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-option-text</value>
      <webElementGuid>8d86cf0d-df67-43b8-b7c1-e2d8c0e1c80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>REGION 4-A</value>
      <webElementGuid>ccb05c3e-9c27-484a-90f2-e98cd5f9061d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-enter-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7d76f4da-a023-4fa3-ab7b-4ea17bce39a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-z-index</name>
      <type>Main</type>
      <value>251</value>
      <webElementGuid>3c236b02-9bc5-4861-8b18-6a1078841fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-font-size</name>
      <type>Main</type>
      <value>14px</value>
      <webElementGuid>5b896fd4-3a33-4058-b222-c89ca0fb73c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-alignment</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>13c0356e-b1e6-4228-8359-79c8ea9142a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-max-width</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>16a07453-1f85-461f-b920-67476bcc8939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-ellipsis-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d195ef96-c2cd-4c50-96aa-38a992154f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-allow-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fa027ea-faab-40f3-b6a2-fe05f3fb5252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            REGION 4-A
          </value>
      <webElementGuid>a4889940-c54e-4264-a1e5-16f312a49245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-970-2&quot;)/span[@class=&quot;vscomp-option-text&quot;]</value>
      <webElementGuid>cf69b700-e63f-445c-bfda-c30c853e7b16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-970-2']/span</value>
      <webElementGuid>a0961323-6d4c-45e2-8500-dcb99d08fbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NCR'])[1]/following::span[1]</value>
      <webElementGuid>30287672-478b-4235-bef7-3944fb77b270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAR'])[1]/following::span[2]</value>
      <webElementGuid>e8c1bdca-0419-4fc0-871c-8c52d12aea8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGION 4-B'])[1]/preceding::span[1]</value>
      <webElementGuid>39757442-cc6e-4fcf-b37b-cca785193471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGION I'])[1]/preceding::span[2]</value>
      <webElementGuid>e950392e-bd5a-49ac-ab5d-121a8d7fa46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REGION 4-A']/parent::*</value>
      <webElementGuid>67f1d878-1d9b-43e4-8d8f-42d287498d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>fc328ba0-4964-450c-9a96-f5567bb732a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            REGION 4-A
          ' or . = '
            REGION 4-A
          ')]</value>
      <webElementGuid>3aae6b59-10fc-4c8a-8ba3-3dae0ad1edae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
