<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Stock Date Acquisition_stockdate</name>
   <tag></tag>
   <elementGuidId>aabf405d-5393-4600-8fb8-9537ada0e979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stockdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stockdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9587edf-4b25-4578-9bc3-b2743d7bdb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>5743de37-295f-4fd0-ade3-b874c25f4cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>8f45b514-0560-430a-a5f6-ed38d71a6c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stockdate</value>
      <webElementGuid>19b97cf1-db04-4330-82d5-ea5985be6993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stockdate&quot;)</value>
      <webElementGuid>731e4d65-061d-4560-abd0-1a1e78a836fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stockdate']</value>
      <webElementGuid>b135098b-e585-4ac8-a060-220580380f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b48-Column2']/div/span/input</value>
      <webElementGuid>e6faa8e8-21b0-481e-b07e-29e1594275d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/span/input</value>
      <webElementGuid>30a988f9-718f-4300-a111-7171dace4076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'stockdate']</value>
      <webElementGuid>19dd226c-5775-47ef-9fba-9a4e7065a7cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
