<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ImmediateContact Person_Immediate_Con_5c3087</name>
   <tag></tag>
   <elementGuidId>a5c5ce92-fc5d-4a5b-9486-4bb1fbbda654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Immediate_ContactPerson</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Immediate_ContactPerson']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>794429a0-e4c8-4ab4-be3e-f5abca26b20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>7a3c53d6-ac73-46d1-9a68-9d522751d815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>365865fd-9ea5-4584-b054-6559b928e54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0c22c17d-9384-4ee7-9abf-56fda0b6a9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Immediate_ContactPerson</value>
      <webElementGuid>95f86fb9-bc71-4639-973a-dcb42ba3eb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Immediate_ContactPerson&quot;)</value>
      <webElementGuid>768af93c-1998-4f72-8f06-7e858821b846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Immediate_ContactPerson']</value>
      <webElementGuid>90f37955-e8ad-4503-b381-a4ef136d0800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b45-Column1']/div/span/input</value>
      <webElementGuid>2a79123a-4b81-41f8-a0d8-ceb4f4a81719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aff8b692-5a94-4c0d-a4bf-e0a7e1fa8150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Immediate_ContactPerson']</value>
      <webElementGuid>fde0b5a1-d205-4b98-9bc4-9b59d4d8b621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
