<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_ImmediateContactNumberS</name>
   <tag></tag>
   <elementGuidId>68d92f8b-4ae8-437a-8447-eaa9175c9ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ImmediateContactNumberS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ImmediateContactNumberS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18f8b5e6-c60d-4262-9e38-03a3097013a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>3050740a-1e4f-40df-bd52-71f4a633dcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bfc234d3-ee49-4a1b-8f80-35050c611db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0ac5edb6-4b7b-414f-b075-4da07b1bad80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ImmediateContactNumberS</value>
      <webElementGuid>f351bb05-1d99-479c-8c59-c8c850943343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a812931e-820b-4a0f-986b-8135ae41175f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>905 123 45</value>
      <webElementGuid>14576b60-4cc4-4bca-acd3-d89bfac6b2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3c4cec1c-9f67-439c-a109-15e1b657d16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ImmediateContactNumberS&quot;)</value>
      <webElementGuid>d405aa39-a082-42c1-9013-028a1f37f62d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ImmediateContactNumberS']</value>
      <webElementGuid>a129c098-c2a3-4a2b-83f4-837344087124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b46-Column1']/div/span/div/input</value>
      <webElementGuid>242feec1-305c-4805-83be-c4a5bc1984dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e2c3a27b-4175-4e65-a79f-b47bbc2cfa7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ImmediateContactNumberS' and @placeholder = '905 123 45']</value>
      <webElementGuid>c21073cb-72e7-49e7-b60e-d0f150d53861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
