<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Number_FinalstepAccountNumber</name>
   <tag></tag>
   <elementGuidId>fddaf16f-a934-44f5-8fe5-4daba079e995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FinalstepAccountNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FinalstepAccountNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bd13cd5-fc90-4dbc-a29e-b6fe6c4d2da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>4515abbc-9b62-4fd2-8365-3d8bc02706c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>afbe75fc-a95b-4bad-b2bc-5a6220d283ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>33c2c65a-dc39-4c97-be71-a88258303708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>e2fe8acf-b9b0-4ab4-b32b-f23ff8f546bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FinalstepAccountNumber</value>
      <webElementGuid>c14244d2-37c2-495c-803b-22b7af3814a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FinalstepAccountNumber&quot;)</value>
      <webElementGuid>537cd079-6fcc-4c0b-a95b-695e88846dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FinalstepAccountNumber']</value>
      <webElementGuid>b12aa236-a6e2-40ed-909c-cdf7aca3499e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b48-Column1']/div/span/input</value>
      <webElementGuid>11e3d004-0eca-4cad-a7f1-196a959f5187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/input</value>
      <webElementGuid>35fc433d-e7b3-4fb7-a95c-cd36921af463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'FinalstepAccountNumber']</value>
      <webElementGuid>3e9ff3be-07e4-4c5b-ac9f-26dba997bbe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
