<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Immediate Address_ImmediateContactNumber2</name>
   <tag></tag>
   <elementGuidId>c7ac1f56-c8ed-4108-b480-162b7e425cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ImmediateContactNumber2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ImmediateContactNumber2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f6b5c2c-355f-492b-bd68-1f99fe9f7ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>4001461a-11c2-4cea-b682-36f33abcc281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c467026b-a501-408e-90bf-8255dcef9c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ImmediateContactNumber2</value>
      <webElementGuid>ebeff061-844e-46ef-aba7-d02797d943fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ImmediateContactNumber2&quot;)</value>
      <webElementGuid>a02450ad-bbf7-4578-aed8-0958cbc3a8e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ImmediateContactNumber2']</value>
      <webElementGuid>4fe66600-d1d0-4ea8-a39f-1f068f144af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b46-Column2']/div/span/input</value>
      <webElementGuid>9d1fd72d-f11c-4e22-969e-19ed0f0796f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>8e8f3235-c9bf-4191-b5e0-316e02f29e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ImmediateContactNumber2']</value>
      <webElementGuid>f8da7485-2c24-45dc-acb1-d3593ef6cacd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
