<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Close</name>
   <tag></tag>
   <elementGuidId>a5bdd2f4-0051-4e26-9581-5f1c863f3b31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.whiteshadow.ThemeGrid_Width4.ThemeGrid_MarginGutter > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-Column2']/div/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2109279b-0575-44d9-a229-68a471604d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Close</value>
      <webElementGuid>947b885f-0498-422c-bedc-6d529c18de5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Column2&quot;)/div[1]/button[@class=&quot;btn btn-primary whiteshadow ThemeGrid_Width4 ThemeGrid_MarginGutter&quot;]/span[1]</value>
      <webElementGuid>08120812-b17a-43c0-9ba7-4b12458eb0fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-Column2']/div/button[2]/span</value>
      <webElementGuid>c212aa6d-afa8-42ed-bca2-36f2f1f72a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STOCKHOLDER ENROLLMENT PREVIEW'])[1]/following::span[2]</value>
      <webElementGuid>badc3a7e-f7db-4c71-b72b-d3cef41e8b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANK INFORMATION'])[1]/preceding::span[1]</value>
      <webElementGuid>5567644e-47a5-43d4-8ecf-5c291706f1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution'])[1]/preceding::span[1]</value>
      <webElementGuid>4ab248eb-34eb-4b15-890d-cfe5a1752c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/button[2]/span</value>
      <webElementGuid>b16efb7e-f579-45f3-927c-eb5f3958a3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Close' or . = ' Close')]</value>
      <webElementGuid>8c366770-612d-4c34-87eb-3388a69fce53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
