<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PDF_b10-MainContent</name>
   <tag></tag>
   <elementGuidId>2aea3d5c-f783-4eb4-bcd8-c59b9619cf11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b10-MainContent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b10-MainContent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>45b88fe7-29c0-4c52-972c-035e4469efb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout-print-main-content layout-print-contain-contents</value>
      <webElementGuid>c7b3f013-1508-4e48-ad7b-ace87be75be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b10-MainContent</value>
      <webElementGuid>6e1b2396-2f1d-4eee-ab22-78cca681bccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b10-MainContent&quot;)</value>
      <webElementGuid>20b92402-f9ce-4c52-8d9b-5a7fcbbb03f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b10-MainContent']</value>
      <webElementGuid>b0ff505e-527d-4a0a-830c-7f448a14565e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b10-LayoutPrint']/div[3]</value>
      <webElementGuid>b52e63f1-3695-4615-86dd-1a49ba4fb42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/following::div[10]</value>
      <webElementGuid>136e4992-a864-4758-a79f-3e88d8a101ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b10-MainContent', '&quot;', ')')])[1]/preceding::div[4]</value>
      <webElementGuid>73427c33-d238-4e58-a692-4ee3032974f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::div[6]</value>
      <webElementGuid>66eb5a35-7f02-4ad5-8965-2ebd99bdaaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>93cac372-3d33-4d3c-b4f3-b0a18cb9e1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b10-MainContent']</value>
      <webElementGuid>513f5394-cb23-4671-a54e-e2fb63f8cadf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
