<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Laoag_vscomp-clear-icon</name>
   <tag></tag>
   <elementGuidId>f8f0bc3b-4f24-45f7-8363-c3aa75a02380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-ele-wrapper-1666']/div/div/span[2]/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9c6204ce-eb6c-4cd5-9847-8991bd630278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-clear-icon</value>
      <webElementGuid>122a3c62-d280-424e-87bb-e88109986fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-ele-wrapper-1666&quot;)/div[@class=&quot;vscomp-toggle-button&quot;]/div[@class=&quot;vscomp-value&quot;]/span[@class=&quot;vscomp-value-tag&quot;]/span[@class=&quot;vscomp-value-tag-clear-button&quot;]/i[@class=&quot;vscomp-clear-icon&quot;]</value>
      <webElementGuid>16a6527e-e619-4c75-941c-1c955b50da2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-ele-wrapper-1666']/div/div/span[2]/span[2]/i</value>
      <webElementGuid>14c919b9-2404-4e95-8765-5a8750658824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span[2]/i</value>
      <webElementGuid>0680e66c-1cd0-4d76-af2e-87b0ea1005fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
