<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__checkbox-icon_1</name>
   <tag></tag>
   <elementGuidId>cf8ee6f4-d892-4ad1-af1e-0ef802e255b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-1666-13']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-1666-13 > span.checkbox-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7ec4dc0-f394-4642-818e-84b25582d00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-icon</value>
      <webElementGuid>7e182c66-e4f9-41c7-895d-aedb5e1bb3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-1666-13&quot;)/span[@class=&quot;checkbox-icon&quot;]</value>
      <webElementGuid>25067513-c061-4e8e-af20-18e80a8a8e1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-1666-13']/span</value>
      <webElementGuid>4398385f-14e8-46da-95f3-f818c5724944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[2]/div/div/span</value>
      <webElementGuid>e632125b-32c8-4fed-a0c1-ebe279cc735f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
