<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__checkbox-icon</name>
   <tag></tag>
   <elementGuidId>89d84d58-f56d-4d7c-b5d3-8641ad449eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-6316-0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-6316-0 > span.checkbox-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>65b1a272-ccb9-431a-8212-057a9684dc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-icon</value>
      <webElementGuid>2fa89d3c-2134-458d-8b60-de93dfeea90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-6316-0&quot;)/span[@class=&quot;checkbox-icon&quot;]</value>
      <webElementGuid>c158b186-9e73-4a65-a18f-434ff0dd3666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-6316-0']/span</value>
      <webElementGuid>62e6a0a8-7dfd-4f0d-ade3-4d67072bf77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>5b07d92f-c23b-4281-bc57-78dff8ff2ae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
