<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create New Stockholder_submenu-2-icon</name>
   <tag></tag>
   <elementGuidId>51936713-6822-49a9-88bd-af9163f1c9d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.submenu-2-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b4-TitleContainer']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ccf818c-bc47-48d5-acda-4d5a62b8475b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-2-icon</value>
      <webElementGuid>dc1226a9-0307-4716-b589-9ffe37310dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-TitleContainer&quot;)/div[@class=&quot;submenu-2-icon&quot;]</value>
      <webElementGuid>a30229f9-769b-4e66-86b1-ca6a13880f1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-TitleContainer']/div[2]</value>
      <webElementGuid>34f1cd14-7ee7-4866-b500-82f7b162a44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>5ff850fc-cbfa-466b-a154-5f9d1fa7ff95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
