<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stockholder Information_osui-submenu__h_be17fb</name>
   <tag></tag>
   <elementGuidId>54b47e2b-6deb-4e7d-8d5f-b1b1e426dc48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b3-SubMenuHeader > div.osui-submenu__header__icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b3-SubMenuHeader']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4d1de96-f5f8-4d42-a37a-93c2173bdc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__icon</value>
      <webElementGuid>c8100b59-6727-4a6f-91f8-e23a052c67d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-SubMenuHeader&quot;)/div[@class=&quot;osui-submenu__header__icon&quot;]</value>
      <webElementGuid>4a1e0244-f9e7-4709-a004-7f70d5147804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-SubMenuHeader']/div[2]</value>
      <webElementGuid>cf5d60a6-06f1-4382-88cd-6006e6d163a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>290d958c-444e-4699-a17d-1ebfeb400e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
