<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_DateOfbirths</name>
   <tag></tag>
   <elementGuidId>bae69b71-b855-4cd9-936f-c5782e263db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DateOfbirths</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DateOfbirths']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>484a3203-5952-4884-b5e2-90685c983c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>8ebab430-fdb9-4133-9cde-fa4edbc8d527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ea3ae9c1-609e-417a-aedc-bdbd6b3635a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DateOfbirths</value>
      <webElementGuid>f2bef057-953e-4a6e-b8fe-4a22db21e238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DateOfbirths&quot;)</value>
      <webElementGuid>a2e28095-0446-479d-b3ff-7ed97edd52ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DateOfbirths']</value>
      <webElementGuid>9ebd6b1d-9194-4db2-9bee-3c1b1319ed11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DOB']/span/input</value>
      <webElementGuid>6a1127a4-0e4d-47ae-a3bd-45b933f07302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/span/input</value>
      <webElementGuid>f09df9c9-2541-43bd-9271-e7ced1f457bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'DateOfbirths']</value>
      <webElementGuid>2d3ba7dd-8425-4959-a3a5-0985f7f5675a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
