<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle Name_Input_FirstName2</name>
   <tag></tag>
   <elementGuidId>9b7ae9a8-3a44-4d74-a478-b3ac73be4149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_FirstName2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_FirstName2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4e4d325-c035-4942-9f10-ef45f8697290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>523b9e12-40f1-493c-8949-dc3966dcff3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b23ba75b-27f5-42f1-91fa-977db9467df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1330e94b-e8e4-406c-8227-dd643ab26b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_FirstName2</value>
      <webElementGuid>352a8df2-e725-4aba-b3c2-adabc1358114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_FirstName2&quot;)</value>
      <webElementGuid>8001df37-6000-4bc7-8109-2ef578539511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_FirstName2']</value>
      <webElementGuid>1e50e91d-9b12-4d22-a2a6-9e5f31034081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b40-Column4']/div/span/input</value>
      <webElementGuid>e683ad56-6a14-41e1-99ff-5e29d567c2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/input</value>
      <webElementGuid>77e5d70b-b90e-42e1-b666-4f6958f63489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_FirstName2']</value>
      <webElementGuid>a4bcab16-cecf-4480-b2bb-92bbec2b6f1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
