<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stock Admin System  DashboardOverall St_025d3a</name>
   <tag></tag>
   <elementGuidId>7b7d13f9-ffdc-4081-be24-61141f4c0e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b1-MainContentWrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-MainContentWrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bec78eda-6cd5-4195-9b23-de82bac713ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-content ThemeGrid_Container</value>
      <webElementGuid>207ff838-0194-4a07-8a6a-2a2b3b44aaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>0b84d2f3-1248-462d-b430-7e9026acda41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-MainContentWrapper</value>
      <webElementGuid>1e7f3447-a2de-4722-a65d-177f9dde5ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock Admin System / DashboardOverall Stocks23Share6000Amount123232-13131App AdminJamesBundalian15Total Share3000Total AmountBranchTotal SharesAmountAgoo00Alaminos00Atimonan153000Baguio00Barleta00Barotac Nuevo00Bay00BayBay00Boracay00Buhangin001 to 10 of 83 itemsInsert the page number to go to...of 9 pages8Total Share3000Total AmountBranchTotal SharesAmountBacoor00Balanga00Balayan00Batangas83000Bulacan00Cagayan De Oro00Calamba00Cavite00Dagupan00Dasmarinas001 to 10 of 36 itemsInsert the page number to go to...of 4 pages0Total Share0Total AmountBranchTotal SharesAmountNo Record Found!0Total Share0Total AmountBranchTotal SharesAmountNo Record Found!</value>
      <webElementGuid>c7a056ca-7007-44f3-ba05-367234b484a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-MainContentWrapper&quot;)</value>
      <webElementGuid>795450ec-a4d0-4bfc-93c5-a5545778c3d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContentWrapper']</value>
      <webElementGuid>e83d5a10-6b7a-4fbc-ac4e-e9cd1fa1630a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-Content']/div</value>
      <webElementGuid>2380a2be-d799-4532-b6ab-e13b46b2a3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No new messages'])[1]/following::div[7]</value>
      <webElementGuid>f3d63ad9-7ba9-4485-8382-068d6504c9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTIFCATION CENTER'])[1]/following::div[10]</value>
      <webElementGuid>a8834a25-2c8d-45ff-bdf0-8b2ce9ea1797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div</value>
      <webElementGuid>e9887aed-b664-4db8-8c84-0f20ec220d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b1-MainContentWrapper' and (text() = 'Stock Admin System / DashboardOverall Stocks23Share6000Amount123232-13131App AdminJamesBundalian15Total Share3000Total AmountBranchTotal SharesAmountAgoo00Alaminos00Atimonan153000Baguio00Barleta00Barotac Nuevo00Bay00BayBay00Boracay00Buhangin001 to 10 of 83 itemsInsert the page number to go to...of 9 pages8Total Share3000Total AmountBranchTotal SharesAmountBacoor00Balanga00Balayan00Batangas83000Bulacan00Cagayan De Oro00Calamba00Cavite00Dagupan00Dasmarinas001 to 10 of 36 itemsInsert the page number to go to...of 4 pages0Total Share0Total AmountBranchTotal SharesAmountNo Record Found!0Total Share0Total AmountBranchTotal SharesAmountNo Record Found!' or . = 'Stock Admin System / DashboardOverall Stocks23Share6000Amount123232-13131App AdminJamesBundalian15Total Share3000Total AmountBranchTotal SharesAmountAgoo00Alaminos00Atimonan153000Baguio00Barleta00Barotac Nuevo00Bay00BayBay00Boracay00Buhangin001 to 10 of 83 itemsInsert the page number to go to...of 9 pages8Total Share3000Total AmountBranchTotal SharesAmountBacoor00Balanga00Balayan00Batangas83000Bulacan00Cagayan De Oro00Calamba00Cavite00Dagupan00Dasmarinas001 to 10 of 36 itemsInsert the page number to go to...of 4 pages0Total Share0Total AmountBranchTotal SharesAmountNo Record Found!0Total Share0Total AmountBranchTotal SharesAmountNo Record Found!')]</value>
      <webElementGuid>e7e560a8-dbc3-4910-81b6-bf98b79ac35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
