<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle Name_Input_FirstName2</name>
   <tag></tag>
   <elementGuidId>d2416a66-b869-43e3-a747-92f9d3daeeb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_FirstName2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_FirstName2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaed4f08-5540-4d5b-b832-125e382a1d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>1aa77e64-dd60-4aa0-9a24-e8f0fa38f237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b14da19-fef6-4f3c-b481-71a4432cb11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>cde750b4-2829-4471-8570-9820b3d71a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_FirstName2</value>
      <webElementGuid>767e089d-dfd4-4851-9d27-124b7ad98fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_FirstName2&quot;)</value>
      <webElementGuid>71512a2c-ed1d-4b2d-b45d-2b299e5a2248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_FirstName2']</value>
      <webElementGuid>cec97a4f-2496-47d7-8689-d7a7c43e6d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b32-Column4']/div/span/input</value>
      <webElementGuid>ce34c49b-1f20-49de-9400-2d2401e5513f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/input</value>
      <webElementGuid>fa1c16c5-892f-4d20-99a4-e3f529759d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_FirstName2']</value>
      <webElementGuid>3059c503-e2bf-4053-a32f-c1ab30cb0f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
