<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_DateOfbirths</name>
   <tag></tag>
   <elementGuidId>8419a05e-fc19-41d2-b721-667cad76e4ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DateOfbirths</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DateOfbirths']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6b77df7-0740-4a2e-99f6-619cf304902a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>149fe7cb-4924-42c1-b5cf-51b97ccd7e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>045d4820-3f5e-408d-8082-9048712d6d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DateOfbirths</value>
      <webElementGuid>bea9084a-cd9e-4ce5-82f1-d22d72cc0a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DateOfbirths&quot;)</value>
      <webElementGuid>62ea7498-dea3-464f-9aba-946a1ed81e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DateOfbirths']</value>
      <webElementGuid>71b35d3f-0722-42b1-881c-bbe41372d70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DOB']/span/input</value>
      <webElementGuid>3f83bd8d-245c-4ac3-bc57-7938d69c5f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/span/input</value>
      <webElementGuid>4d0ba7d4-eefd-49dd-8a88-e7f223b692f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'DateOfbirths']</value>
      <webElementGuid>981142f9-6eb5-46be-b6bb-55bb4f2e2bd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
