<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--ResignedActiveInactiveOthers</name>
   <tag></tag>
   <elementGuidId>c24524cf-0b24-4e0b-abef-e505db7272b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#StockholderStatus2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StockholderStatus2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f2d19e7a-39fb-4471-a570-2b1da98aac05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>6df670e7-3502-44ef-ad3e-998ef061a402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a4e0dd7-2874-45b0-89a5-2e1082a025de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StockholderStatus2</value>
      <webElementGuid>e62e61ee-87bb-4697-8538-c581a1fe5510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--ResignedActiveInactiveOthers</value>
      <webElementGuid>964dad1a-ea50-4f26-803e-1e4994239c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StockholderStatus2&quot;)</value>
      <webElementGuid>9fd53373-0530-4837-b6bd-cbcad1ece09c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StockholderStatus2']</value>
      <webElementGuid>96b41651-6054-4da7-a59f-6a9178acdcbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StockholderStatus2-container']/select</value>
      <webElementGuid>fa791179-a5ef-42ed-9434-58913195374d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholder Status'])[1]/following::select[1]</value>
      <webElementGuid>9d0f2cac-917c-4ddf-8ddd-5c761c825080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Date Acquisition'])[1]/following::select[1]</value>
      <webElementGuid>663f0a05-a3fb-49b4-8f9b-396b7e4d78b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Type'])[1]/preceding::select[1]</value>
      <webElementGuid>0704c7b7-9efe-4f28-88e7-6a40974538d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>296de2bf-77d5-47c2-a0ec-c15fe3227e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'StockholderStatus2' and (text() = '--Select--ResignedActiveInactiveOthers' or . = '--Select--ResignedActiveInactiveOthers')]</value>
      <webElementGuid>a0ecc628-1d24-4d4e-a36d-57dae85e2fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
