<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--ContactPersonLandLineMobile</name>
   <tag></tag>
   <elementGuidId>45c9e232-ace2-4d34-9bca-12fac10d7f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContactType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ContactType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>234d1392-a263-47f6-9c57-98d5969aeea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>175e82f5-2540-43df-b7cf-c05a9c59160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44055a99-0410-4448-a130-7262b8a0c062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContactType</value>
      <webElementGuid>4d9406cf-7711-4dd9-8217-b3db64e00885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--ContactPersonLandLineMobile</value>
      <webElementGuid>81803338-2d27-485a-a8e7-254f85c3e9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactType&quot;)</value>
      <webElementGuid>09ef58d7-b518-45ce-81d4-069c29131ec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ContactType']</value>
      <webElementGuid>a6192390-ab94-496f-983f-d302bc92c682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactType-container']/select</value>
      <webElementGuid>acefd513-ab36-4369-a387-d26061c450a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Type'])[1]/following::select[1]</value>
      <webElementGuid>157af7bb-267c-468e-8b3d-67dc1032ee3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholder Status'])[1]/following::select[2]</value>
      <webElementGuid>36863d0c-9172-443c-8e67-10d3c3b47304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>1d6e1a2b-3c82-4c88-bc8a-47a93b937134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ContactType' and (text() = '--Select--ContactPersonLandLineMobile' or . = '--Select--ContactPersonLandLineMobile')]</value>
      <webElementGuid>20e76756-e132-442e-b2d8-3a23d255e302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
