<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create New Stockholder</name>
   <tag></tag>
   <elementGuidId>5f4b3189-f0b3-4146-960e-b5ece2dac2e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b4-TitleContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b4-TitleContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c09c974f-c142-46ba-adfa-d3bc9bc27d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-2-title</value>
      <webElementGuid>5d1510e8-2a12-44ec-b262-bb0f3d5bd74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b4-TitleContainer</value>
      <webElementGuid>af2a21a8-b62b-493f-80d8-5a2fbf3c4ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Stockholder</value>
      <webElementGuid>0beb9d20-42f8-4f0e-8311-100ebe36f30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-TitleContainer&quot;)</value>
      <webElementGuid>1885ff3f-7ce3-484b-9f00-297861e8d58a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-TitleContainer']</value>
      <webElementGuid>74da9e9a-73c6-4143-9799-5ad06f54a4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-$b4']/div/div</value>
      <webElementGuid>78b11905-daac-47a8-9fee-bf2207e59449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholder Information'])[1]/following::div[5]</value>
      <webElementGuid>0bbc9245-78e8-4e70-b51d-470445fc3ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::div[9]</value>
      <webElementGuid>ca77758a-1961-4da5-aa78-90b893969f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::div[3]</value>
      <webElementGuid>9637c2eb-43b1-4ae9-8275-4ca1decf14af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>8ba803ed-0be4-45ae-9d2f-8f62481e2582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b4-TitleContainer' and (text() = 'Create New Stockholder' or . = 'Create New Stockholder')]</value>
      <webElementGuid>53ee517e-efa5-45ed-bde0-e41f0d6ec9f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
