<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create New Stockholder_submenu-2-icon</name>
   <tag></tag>
   <elementGuidId>41513bc5-952f-41e6-82a9-b578125ec30b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.submenu-2-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b4-TitleContainer']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8d78e66-b37f-4041-8cda-79035cdc1978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-2-icon</value>
      <webElementGuid>2f24bebf-f97d-4539-8da3-b399b7d07377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-TitleContainer&quot;)/div[@class=&quot;submenu-2-icon&quot;]</value>
      <webElementGuid>5f6ab3c1-4eff-43fd-b4a6-d68994de2607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-TitleContainer']/div[2]</value>
      <webElementGuid>e61affd8-b9dd-4cb2-9c95-69a74896f820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>ad2de360-e142-4435-ac02-728380c53d23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
