<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--MemberNonMemberStaff (2)</name>
   <tag></tag>
   <elementGuidId>1d467f47-74a1-4688-b643-3b226ecfd5d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownClientType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownClientType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2fcab79e-4eed-44fb-b08d-8c1d655fa868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>e47de271-eca0-4c7f-be20-bc5c4b31df0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b4787bf-a213-4f63-9afd-819d95ece71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownClientType</value>
      <webElementGuid>d9ff8b29-4c93-4ed0-901e-d39bdc6a9e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--MemberNonMemberStaff</value>
      <webElementGuid>3d334472-73f7-4a47-be70-e82dd2d18a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownClientType&quot;)</value>
      <webElementGuid>8cdebcfd-71c4-46ab-bee1-aea19607ce93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownClientType']</value>
      <webElementGuid>fc8749c7-c5a4-4023-a5e7-8e34c148b455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownClientType-container']/select</value>
      <webElementGuid>9625cdb9-2637-41d5-ad69-69eaad97efa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Types'])[1]/following::select[1]</value>
      <webElementGuid>2afa81b9-c872-4499-a3da-1f38d2574e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auditlogs'])[1]/following::select[1]</value>
      <webElementGuid>1ba1f45c-0245-4d79-acec-09c71d90d961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Stockholder'])[1]/preceding::select[1]</value>
      <webElementGuid>966a8bb7-71b7-45c3-a408-fde5156766da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tagkawayan 123232-13131'])[1]/preceding::select[2]</value>
      <webElementGuid>f95d33dd-d728-441f-97fb-ba974da474e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>60ab8a97-9e8c-4ab4-9298-334e09a1e434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownClientType' and (text() = '--Select--MemberNonMemberStaff' or . = '--Select--MemberNonMemberStaff')]</value>
      <webElementGuid>852b6e60-15b7-45ba-9695-8c909e0fe5d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
