<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Individual ShareholderCorporate Shareholder</name>
   <tag></tag>
   <elementGuidId>b91595ab-c216-49c9-a8b4-0e5078415f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownStockholderType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownStockholderType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f9fdf2eb-ada7-4947-a111-22b89286e9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>5398e198-75f1-47f2-8edb-5ecc2dcaac95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4539dc8e-f542-4baf-9695-225c14c76bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownStockholderType</value>
      <webElementGuid>4b61d138-f69f-4cad-a880-fc462bbfec7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Individual ShareholderCorporate Shareholder</value>
      <webElementGuid>3ee2ef4d-a814-4a0c-b97a-82193b168558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownStockholderType&quot;)</value>
      <webElementGuid>29328190-b865-4932-9e0e-b3003249f44c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownStockholderType']</value>
      <webElementGuid>e72abd8f-a2de-440c-9000-e98c1a7be8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownStockholderType-container']/select</value>
      <webElementGuid>cfad278f-d2bc-4aac-889a-dae74e7e119b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Stockholder'])[1]/following::select[1]</value>
      <webElementGuid>44365116-48b2-41a5-b710-3d4c48cd86ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Types'])[1]/following::select[2]</value>
      <webElementGuid>d91516bc-6270-4df2-981f-ad1ed144f69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tagkawayan 123232-13131'])[1]/preceding::select[1]</value>
      <webElementGuid>7be55087-ed26-4128-abf6-031b91cfa0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Admin'])[1]/preceding::select[1]</value>
      <webElementGuid>76d168d5-7f09-4bce-bd00-7ec7c40636b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>9b71748a-bf86-458d-8625-9f8e712b9f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownStockholderType' and (text() = '--Select--Individual ShareholderCorporate Shareholder' or . = '--Select--Individual ShareholderCorporate Shareholder')]</value>
      <webElementGuid>dae3b28f-1df1-4c85-a5d5-17d8ee64683b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
