<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--MemberNonMemberStaff</name>
   <tag></tag>
   <elementGuidId>09856a1f-a29b-4bbf-a3c9-9d81a0992cc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DropdownClientType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DropdownClientType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1349d69e-77f9-4db7-bf50-0aa58c46a0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>467952a7-19b5-4697-ac13-9628b3b8a407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a51984d-d7b6-4f92-8974-56e91501e828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DropdownClientType</value>
      <webElementGuid>fdab2d0e-2a95-4ea0-8a0e-b8fc61c5026c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--MemberNonMemberStaff</value>
      <webElementGuid>8f1cb48c-2c57-4aec-bb89-29bc82bee283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DropdownClientType&quot;)</value>
      <webElementGuid>9ad1f663-6c37-4253-8333-4093f98a4de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DropdownClientType']</value>
      <webElementGuid>901dfd0b-b33f-4ceb-b8b3-636acf8d0ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DropdownClientType-container']/select</value>
      <webElementGuid>4ffe3dfa-d849-482f-9163-406ffd24fb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Types'])[1]/following::select[1]</value>
      <webElementGuid>64165399-3ee7-45e6-a25b-32ea2ee9eb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auditlogs'])[1]/following::select[1]</value>
      <webElementGuid>4a79053b-fa95-41ff-b602-4bf85acbc00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Stockholder'])[1]/preceding::select[1]</value>
      <webElementGuid>4170e86b-d232-43da-b546-2cb606115d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tagkawayan 123232-13131'])[1]/preceding::select[2]</value>
      <webElementGuid>716d5090-33c2-4b61-ad2c-02f8429dad62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>01a6ab53-ffd3-4ec9-a89b-e48aadcd1230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DropdownClientType' and (text() = '--Select--MemberNonMemberStaff' or . = '--Select--MemberNonMemberStaff')]</value>
      <webElementGuid>f4faab42-9c73-4638-b635-983a43b7298c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
