<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Total Amount_icon fa fa-chevron-circle-do_7ca990</name>
   <tag></tag>
   <elementGuidId>c3d2710b-65dc-43b0-93eb-c315f234af92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-chevron-circle-down.fa-1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l1_0-48_0-b5-IconOpen']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>666f7cbb-5b79-480a-82a4-0ec34131c00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-chevron-circle-down fa-1x</value>
      <webElementGuid>b70217c5-be76-4db7-a738-a92741011c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1_0-48_0-b5-IconOpen&quot;)/i[@class=&quot;icon fa fa-chevron-circle-down fa-1x&quot;]</value>
      <webElementGuid>b2f1a18e-4e8e-4294-87e0-d3a36cea10d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l1_0-48_0-b5-IconOpen']/i</value>
      <webElementGuid>a9a2537a-0f18-49a4-9ca6-6801cf00c663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
      <webElementGuid>a9cdb300-583b-4161-9e59-4ad73392dc5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
