<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_Input_TextVar</name>
   <tag></tag>
   <elementGuidId>e2a4c011-d1d8-4f1b-8e9f-6502e2f3ce66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_TextVar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_TextVar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f4dc965-3302-4954-94d1-59e4b5dfc9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>ad55b078-dee4-48e7-a18c-7a29751bad84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f0c2a7d-492b-4340-9b00-07121903d2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CID/First Name and last Name</value>
      <webElementGuid>0b4be243-db59-4528-af32-f74124a220c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>17868a2f-b448-4028-9487-15e40500eb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_TextVar</value>
      <webElementGuid>8af13469-2142-497a-9101-6fe7125d5829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_TextVar&quot;)</value>
      <webElementGuid>6de330c6-0659-4619-afef-c6f6844e908e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_TextVar']</value>
      <webElementGuid>66c4c0b2-3e17-4ec8-800f-600d60aab2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-Column2']/div/span/input</value>
      <webElementGuid>81d5c617-1cc0-4e84-bf3a-359ae47b781c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dbbf0b30-5b9b-43cf-927e-f42aed15d351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'CID/First Name and last Name' and @id = 'Input_TextVar']</value>
      <webElementGuid>c04b8ad6-17d4-4d96-9f26-454cccb146ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
