<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Utilities</name>
   <tag></tag>
   <elementGuidId>1551a763-7877-4e4f-a0e8-5f228cdd4e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b6-Menu > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b6-Menu']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6962349a-d44c-4a64-b6a6-dee70d8aab09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Utilities</value>
      <webElementGuid>1ed04ffe-938d-4e5b-976b-da6e2dd1adbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-Menu&quot;)/span[1]</value>
      <webElementGuid>e5f7a643-82b5-447b-8f74-b2ee6b15a242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-Menu']/span</value>
      <webElementGuid>97f4b6e3-cb66-4622-bedf-b1ec88155368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master List'])[1]/following::span[1]</value>
      <webElementGuid>e588c41b-dd32-44f6-a4ff-0d2f03118427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User List Reports'])[1]/following::span[2]</value>
      <webElementGuid>691fe6ae-63f5-4384-a3d7-518110f256c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Developers'])[1]/preceding::span[1]</value>
      <webElementGuid>d3f68c0b-d577-4934-ac0c-c078f962611b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Roles'])[1]/preceding::span[2]</value>
      <webElementGuid>504fb58b-fef9-4d66-820c-b315482a1e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Utilities']/parent::*</value>
      <webElementGuid>767742a5-5d0f-42c8-a65b-8e7dd523aaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/span</value>
      <webElementGuid>62d008b4-b6ae-4225-ac04-0a8adf72fe19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Utilities' or . = 'Utilities')]</value>
      <webElementGuid>fd8adb12-7bf8-4305-8689-78ff96c6755f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
