<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7420faa5-9d8a-4718-8992-a9909a9fdbf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-Column1']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>99a14186-3def-4813-9b4d-e60109d6ea6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/STOCKSADMINSYSTEMS/img/STOCKSADMINSYSTEMS.cblogo.png?DHeCyvqHt+jA4rkLBoEk2Q</value>
      <webElementGuid>427cd426-9a60-4b4d-90e5-a23ebc706ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-Column1&quot;)/div[1]/img[1]</value>
      <webElementGuid>1b112d62-b3ca-49e0-ba19-5a7d3b132f70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-Column1']/div/img</value>
      <webElementGuid>6ee58234-c09d-4687-9ad0-ef3d38b5903e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>cf88b750-4f72-4089-aae3-3b6e73f82e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/STOCKSADMINSYSTEMS/img/STOCKSADMINSYSTEMS.cblogo.png?DHeCyvqHt+jA4rkLBoEk2Q']</value>
      <webElementGuid>4bcac7d0-182c-46eb-8558-5dc536898ab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
