<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Adding of Share Type_RadioGroup1</name>
   <tag></tag>
   <elementGuidId>2c435699-02c3-452d-8520-e9148fdb67a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RadioButton1-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RadioButton1-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd3d01ab-0d41-4ab4-86e0-44f9677621dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>68ad7b26-9196-45b4-9197-a8e3abf0a3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RadioButton1-input</value>
      <webElementGuid>8a626706-b5cd-4a0b-b076-5243fb7a412f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>a87db39e-ded2-495b-bd9a-1773793ecdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadioGroup1</value>
      <webElementGuid>47aa73f6-d755-4344-a4a3-f8dfc1409f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Addtomyshare</value>
      <webElementGuid>8fc25369-359b-405a-bdfa-17b3aaa8e255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadioButton1-input&quot;)</value>
      <webElementGuid>bac4fa79-c34a-4693-b585-86b4160e9ca3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RadioButton1-input']</value>
      <webElementGuid>a39f7df3-6bff-48b6-b2be-ae027111940f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadioButton1']/input</value>
      <webElementGuid>d147f615-28f6-46ed-a0be-a2faf0d386b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e628ca9b-f622-4ad1-909e-d26b52503fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'RadioButton1-input' and @name = 'RadioGroup1']</value>
      <webElementGuid>b0041d83-6dd9-4dda-822e-d18d2c50271e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
