<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number Of Shares_Input_NumberOfShares</name>
   <tag></tag>
   <elementGuidId>ec2fc02b-d4f1-47cf-b55b-e23351f9198b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_NumberOfShares</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_NumberOfShares']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87e4453a-878b-4b54-8e07-bd2bb2fee490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>f814f685-f1e8-4d8b-8710-52c66aa9018c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1c115b05-1ab7-4fc5-b13c-d4e4c131a79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>62e10f87-312a-4ece-9615-7a5573a84bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>fc94b41d-0df7-43ea-baa2-02b7c24566d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_NumberOfShares</value>
      <webElementGuid>8a09e511-a0d7-4fb6-8a4a-b49e7f6de448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_NumberOfShares&quot;)</value>
      <webElementGuid>cdad93e2-94ab-48a2-8a5b-643545bc06c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_NumberOfShares']</value>
      <webElementGuid>db04fade-66cc-4c1a-8e47-86d3b80563ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b10-Column2']/div/span/input</value>
      <webElementGuid>dfef062e-7362-404a-a854-b6b5783eec22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>d61fb96a-cea9-4ffc-985b-b2a26f60ff9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Input_NumberOfShares']</value>
      <webElementGuid>158e4d95-5c7a-42a6-913f-e94d32f2c30b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
