<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--SELECT--Common Share StockPreferre_ef6566</name>
   <tag></tag>
   <elementGuidId>d4f7b452-a1bd-49f5-a615-fceb0949265a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b5c97462-874b-4814-80f5-b871bd834c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>f6de1e09-5389-4376-b025-d2fa82ba6a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3dcaf71-9062-4b64-b281-dcfd3f14b4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown5</value>
      <webElementGuid>5f75ef1e-60f5-4b96-a3b4-c8d526d93f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--SELECT--Common Share StockPreferred Share StockTreasury Stocks </value>
      <webElementGuid>54adc49b-1980-40b5-b550-d8e603bffc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown5&quot;)</value>
      <webElementGuid>f3efa8fd-5415-428a-9f70-d990f9f6d2ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown5']</value>
      <webElementGuid>5e16104b-064a-400d-8337-1546f342da9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown5-container']/select</value>
      <webElementGuid>a2f6e038-51b9-41e7-b11b-2d7063893805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Type'])[1]/following::select[1]</value>
      <webElementGuid>b4896144-0995-401a-8c91-e701a1615f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Shares (Via Transfer)'])[1]/following::select[1]</value>
      <webElementGuid>f69538da-1c51-4b4c-b021-85248177b816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number Of Shares'])[1]/preceding::select[1]</value>
      <webElementGuid>9b678bb9-13f7-4007-8212-c72ca5d16d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::select[1]</value>
      <webElementGuid>89fa182b-b5a5-4197-8d02-dab64b132e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d62e7547-5f23-408a-a965-1860a3be5a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown5' and (text() = '--SELECT--Common Share StockPreferred Share StockTreasury Stocks ' or . = '--SELECT--Common Share StockPreferred Share StockTreasury Stocks ')]</value>
      <webElementGuid>372ea913-8fe5-4d21-a633-f79c6b636812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
