<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date Of Recognition_Input_TextVar6</name>
   <tag></tag>
   <elementGuidId>83294ef6-89d6-4c33-8bd6-e26e1a390635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_TextVar6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_TextVar6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edfb6296-9bd5-4154-8f23-91013eba4fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>7ddf8293-6db4-4873-8997-1d479ecf9fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>6cbd576d-4a0a-4ce8-ada8-efbcff007829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_TextVar6</value>
      <webElementGuid>e7c6a4aa-c0f0-41f2-9e38-d9399cda504b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_TextVar6&quot;)</value>
      <webElementGuid>244ef102-21fe-454c-9a01-6b82ca50ccd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_TextVar6']</value>
      <webElementGuid>21e30f63-f359-404a-981e-0dada905a1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b30-Column1']/div/span/input</value>
      <webElementGuid>f38c23e2-29d4-4168-bc1d-a125c962b44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>791601c9-0d61-49b7-84a7-c8278be46aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'Input_TextVar6']</value>
      <webElementGuid>0093b93e-65fa-44a6-914a-4189714ec81b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
