<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CIFID Number_Input_TextVar</name>
   <tag></tag>
   <elementGuidId>5153d17b-3661-4372-a01c-905c396eda6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_TextVar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_TextVar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76d01fab-f894-4bd1-8bbd-03a893862fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>6c4ea21f-a180-4136-9b05-40487af4e61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6770d87-4331-4f43-802e-74ed462ddc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_TextVar</value>
      <webElementGuid>c185feeb-4820-4b37-8ded-3dde056e16ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_TextVar&quot;)</value>
      <webElementGuid>7c39daea-74f5-4aaf-8298-7d5b5968946c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_TextVar']</value>
      <webElementGuid>700d9c02-fc0d-433e-81ba-165a1fcf8e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b30-Column4']/div/span/input</value>
      <webElementGuid>bd1b4463-e54f-4b91-b9aa-076c739a2309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/input</value>
      <webElementGuid>8c28bd05-1d3e-4f13-bc96-4768eb57a6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_TextVar']</value>
      <webElementGuid>1257065f-862f-48ef-a27d-878f9372671d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
