<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--MemberNonMemberStaff</name>
   <tag></tag>
   <elementGuidId>2ac280aa-c4a4-444d-8760-c72c1a8ea26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf0335fb-cf27-41de-9342-d8a237ec726d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>35cd66c6-844c-4bcb-8407-ab63026612eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9636e98-ed14-477d-b96b-40702e43df3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown3</value>
      <webElementGuid>4c47f774-4c3f-450d-ab87-48426bed99cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--MemberNonMemberStaff</value>
      <webElementGuid>bc77df1b-8f6a-4661-b753-53af3bb33f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown3&quot;)</value>
      <webElementGuid>eb38a97b-1e60-44c6-9444-2f93faa8322d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown3']</value>
      <webElementGuid>d4bc28af-fd50-4c7c-a5fd-ee42508eafd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown3-container']/select</value>
      <webElementGuid>a63ebe57-dc46-4ea0-93a6-6de388b5634a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Types'])[1]/following::select[1]</value>
      <webElementGuid>815c0609-be24-45d7-928e-27438deaecb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Stockholder'])[1]/following::select[2]</value>
      <webElementGuid>6f13036e-a3c8-4992-9836-34f71fc9c82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIF/ID Number'])[1]/preceding::select[1]</value>
      <webElementGuid>0f2363d9-4f39-41f5-bd5c-8eff464a2c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>e8f2fa3a-3233-4585-b36f-221530471ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown3' and (text() = '--Select--MemberNonMemberStaff' or . = '--Select--MemberNonMemberStaff')]</value>
      <webElementGuid>390672a2-820e-4147-af33-262c27270808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
