<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Individual ShareholderCorp_3d3b64</name>
   <tag></tag>
   <elementGuidId>b874a791-1781-4e98-a2df-84a184fb06bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>075beb5d-f127-4970-9901-a67693799344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>9411537d-05c4-4d4a-b116-6f279e6e818a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b70932fb-7cd4-408b-ab15-97c3223f748c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown8</value>
      <webElementGuid>bb951d7f-9606-4456-b1f5-9a24c9c1e337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Individual ShareholderCorporate Shareholder</value>
      <webElementGuid>9e104da7-24bb-4f2f-a0ff-31c72f68b2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown8&quot;)</value>
      <webElementGuid>0dd0c411-54a4-4298-aead-95bdf9e3d35a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown8']</value>
      <webElementGuid>452eea68-b01a-4c86-8f96-53c1c66b77e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown8-container']/select</value>
      <webElementGuid>1a413d0a-742e-4eb6-b028-05c6c6e133de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Stockholder'])[1]/following::select[1]</value>
      <webElementGuid>fbf92e5a-2a77-41f6-8714-b53d136ea018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Of Recognition'])[1]/following::select[1]</value>
      <webElementGuid>8f1a3706-a621-4726-845e-b42388743f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Types'])[1]/preceding::select[1]</value>
      <webElementGuid>64d36810-34c6-4525-96f4-42f0da7b0ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIF/ID Number'])[1]/preceding::select[2]</value>
      <webElementGuid>3caf242f-f910-4b05-a1ad-5b4cb59c9632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>b7f0e1ee-23bd-4cc2-8b31-9843ae396ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown8' and (text() = '--Select--Individual ShareholderCorporate Shareholder' or . = '--Select--Individual ShareholderCorporate Shareholder')]</value>
      <webElementGuid>7c8bf127-fe81-490c-9185-e2bfddb92133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
