<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PDF_OSFillParent</name>
   <tag></tag>
   <elementGuidId>aabec848-c8ee-4e84-938f-6a48a4bb8d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l2-40_0-b11-l1-57_0-PrintCertificate']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.OSFillParent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>86027e04-3ff1-4ec2-90d3-fa32c62f03c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent</value>
      <webElementGuid>8da4eed1-4a8b-4484-8958-06be2b0bea4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/STOCKSADMINSYSTEMS/img/STOCKSADMINSYSTEMS.ClearStockCertificatefront.png?PMldyHt9HOvMXUlzsIKDkw</value>
      <webElementGuid>0498dfd0-1946-4abe-bc82-cf07dbde1db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l2-40_0-b11-l1-57_0-PrintCertificate&quot;)/img[@class=&quot;OSFillParent&quot;]</value>
      <webElementGuid>9b508789-6501-4c8d-971d-52c32c4e6422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l2-40_0-b11-l1-57_0-PrintCertificate']/img</value>
      <webElementGuid>cc12c664-f24e-42ba-9909-8992aab989e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/img</value>
      <webElementGuid>963d9c54-1393-4187-b85a-f3ddfce0e91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/STOCKSADMINSYSTEMS/img/STOCKSADMINSYSTEMS.ClearStockCertificatefront.png?PMldyHt9HOvMXUlzsIKDkw']</value>
      <webElementGuid>0e7d94e7-b7b7-4cff-b2e5-9d1dbbfb012e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
