<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select Type--Per InstitutionPer Br_196992</name>
   <tag></tag>
   <elementGuidId>01f4d422-a35b-4427-8f00-293303a3714b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Dropdown1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5e2f928-e5fe-4bdd-a7ac-c290e8db387f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>540eb426-a817-4b09-824d-8b17e742a03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>843ea73b-2398-46f0-8c7e-39327d25db62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown1</value>
      <webElementGuid>f7724b25-1ee7-4a32-9e80-0aaa63b27ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Type--Per InstitutionPer BranchIndividual</value>
      <webElementGuid>c511aa61-0d65-45ad-a963-61fa6d25a6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown1&quot;)</value>
      <webElementGuid>776d236e-e21d-4e89-b185-4c869a1b301c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown1']</value>
      <webElementGuid>71c51a2c-73bd-4ff5-badb-dbe45e9f50f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown1-container']/select</value>
      <webElementGuid>1b3ecb2f-66a7-4222-9b73-a01540320bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution'])[1]/preceding::select[1]</value>
      <webElementGuid>f63a56b8-8c59-4ef9-80ec-faa9dbdc37e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/preceding::select[1]</value>
      <webElementGuid>8191f5cc-780e-4941-bd30-811de5b4008a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>89c6a3fe-76fa-4b7d-8711-40ee109ee691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown1' and (text() = '--Select Type--Per InstitutionPer BranchIndividual' or . = '--Select Type--Per InstitutionPer BranchIndividual')]</value>
      <webElementGuid>becb80c2-97b6-49cd-ae14-38ce0eb7234e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
