<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Generate</name>
   <tag></tag>
   <elementGuidId>43bfc61e-fce0-45be-ad8d-c36dc29ff87c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b8-Column2']/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.OSFillParent > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be4e5715-a22f-4e61-937f-252901d16eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>6e70c64d-86fb-45d2-967c-11126ef8998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b8-Column2&quot;)/button[@class=&quot;btn OSFillParent&quot;]/span[1]</value>
      <webElementGuid>d4412498-4657-4e8e-9031-f640b7b4ee77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-Column2']/button/span</value>
      <webElementGuid>7194493f-32dd-4d96-8590-328285ce80e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date:'])[1]/following::span[3]</value>
      <webElementGuid>b068a10b-75e7-4e0d-bdeb-852bb5b2265b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date:'])[1]/following::span[3]</value>
      <webElementGuid>1e6b4602-685d-4fc2-aef6-56506af7df9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/preceding::span[2]</value>
      <webElementGuid>5d800c28-8e0c-415a-a48e-7b868ce61539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate']/parent::*</value>
      <webElementGuid>5504d3fd-c77c-4237-976d-c83875d0b769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>dcf695ea-2fbb-42a4-9c8b-77db2e07509c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Generate' or . = 'Generate')]</value>
      <webElementGuid>b8be5624-f55f-4260-baaf-bdfd69e36b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
