<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Utilities_osui-submenu__header__icon</name>
   <tag></tag>
   <elementGuidId>42508e65-b260-43f9-adb8-9f05fa0007ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b7-SubMenuHeader']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b7-SubMenuHeader > div.osui-submenu__header__icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7519045f-8da0-4f62-9d96-8ed76fcf8001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__icon</value>
      <webElementGuid>370d5308-e915-450a-bc99-4917aec706dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b7-SubMenuHeader&quot;)/div[@class=&quot;osui-submenu__header__icon&quot;]</value>
      <webElementGuid>cd218869-ffce-4470-84f0-3725fb045e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b7-SubMenuHeader']/div[2]</value>
      <webElementGuid>c94dfc2c-dfed-4558-bd75-4d76f36e2107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]</value>
      <webElementGuid>490428e2-4836-4d48-9f1e-6cad8abe42bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
