<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_Input_UsernameVal</name>
   <tag></tag>
   <elementGuidId>79982792-d2e5-4da2-b026-e8fec2553305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_UsernameVal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_UsernameVal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44c349e9-ece4-4456-9606-ffb2648b1164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>cf5c691f-d6a2-448c-a885-4c6bdc6aaf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce39453c-437d-4372-99f9-05a9714bd740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>e332aa4c-07cc-4a48-ba8b-760f168a330d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_UsernameVal</value>
      <webElementGuid>35709398-eeb2-4f0d-84b1-c6fe8d0059a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_UsernameVal&quot;)</value>
      <webElementGuid>2efc0613-692b-4811-a964-7c6ed7d7bba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_UsernameVal']</value>
      <webElementGuid>170ee04a-c30c-4947-be3d-f10822d6b088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-Input']/span/input</value>
      <webElementGuid>a084bfb4-da65-4e4a-8ed3-5a3ca12120fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>68ae461b-63ec-4562-8899-67bd6419c257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_UsernameVal']</value>
      <webElementGuid>9ba44616-5211-4457-964f-7710a7bad9d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
