<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Stockholder Inquiries 360</name>
   <tag></tag>
   <elementGuidId>ca8ab1e9-0bd8-4a1e-ba2f-a51bffd09677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b3-Items']/a[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8623c021-f3ea-4437-b480-680865e72120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stockholder Inquiries 360</value>
      <webElementGuid>ec6dfdb2-ae0f-4d85-aa40-e48cfdc11a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-Items&quot;)/a[@class=&quot;ThemeGrid_MarginGutter&quot;]/span[1]</value>
      <webElementGuid>f5287afe-048f-47fe-a74c-3e38caf26193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-Items']/a[3]/span</value>
      <webElementGuid>a2a57175-eb48-4d5b-b289-f35327a6eef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Stock Certificate'])[1]/following::span[1]</value>
      <webElementGuid>e79f5aae-799c-4d85-86a8-db94ed94e3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholders Amendment'])[1]/following::span[2]</value>
      <webElementGuid>4c12e109-9f51-45b2-8a62-9ecce6d41442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/preceding::span[1]</value>
      <webElementGuid>afc637ca-b86f-4203-814a-a71af2857cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User List Reports'])[1]/preceding::span[2]</value>
      <webElementGuid>1b4454c6-76c2-4763-a26e-80ee60e360b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stockholder Inquiries 360']/parent::*</value>
      <webElementGuid>dc419dd3-b791-4b79-b94e-6bc949b2f608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>27a16557-c84d-48b4-8785-a0de2ec378d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Stockholder Inquiries 360' or . = 'Stockholder Inquiries 360')]</value>
      <webElementGuid>4fb7a247-c088-4cde-9349-752684fc0309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
