<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cavite</name>
   <tag></tag>
   <elementGuidId>d77f7440-acf7-4e9e-9610-b105ff69ee50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-5725-3 > span.vscomp-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-5725-3']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ba34de5-fa99-4a5e-96df-a73778ee6e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-option-text</value>
      <webElementGuid>c59a7bef-4cc1-4805-921e-353b8ab83cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Cavite</value>
      <webElementGuid>e7ad01db-932d-401f-860a-19e64b8fe6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-enter-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>03e23cc6-4fa0-4e56-ac96-f917c70ec9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-z-index</name>
      <type>Main</type>
      <value>251</value>
      <webElementGuid>d02b5f2e-34e2-4ba8-a800-0c28647e1f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-font-size</name>
      <type>Main</type>
      <value>14px</value>
      <webElementGuid>11887e8e-c4b6-4dff-8832-9e95c789eff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-alignment</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>183058a1-109b-46db-956d-96a5ebe685e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-max-width</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>090e649b-539b-44db-bde6-4599d2fc7721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-ellipsis-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e5eaa31a-99f6-40cd-9a0b-fbdf9d9c78ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-allow-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8086556-3922-4733-9159-89314c6d8e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Cavite
          </value>
      <webElementGuid>fe067eac-e22b-4fad-899a-c92766ce8c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-5725-3&quot;)/span[@class=&quot;vscomp-option-text&quot;]</value>
      <webElementGuid>448109c5-5d31-4ec5-b1a6-c0618c7938d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-5725-3']/span</value>
      <webElementGuid>19049fed-0ae5-4571-a49a-5d6798a4c1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CamSur'])[1]/following::span[1]</value>
      <webElementGuid>fd2ebffc-5404-4e0e-98da-b85212b53a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batangas'])[1]/following::span[2]</value>
      <webElementGuid>b916e788-bb9a-499f-91bf-fcfab4febc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cebu'])[1]/preceding::span[1]</value>
      <webElementGuid>e3e70cf9-1906-4b25-a0d2-b3d6d07f2277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GMA'])[1]/preceding::span[2]</value>
      <webElementGuid>da40d5f0-1acf-4268-98b7-5a22874823b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cavite']/parent::*</value>
      <webElementGuid>721db6a4-d0fe-4aff-aa44-ce2d12cd1f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>49b1250b-7d5b-421b-b9e0-24157ed967f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            Cavite
          ' or . = '
            Cavite
          ')]</value>
      <webElementGuid>592bc88f-6b2e-42ba-9bc2-e99ab6804dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
