<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_COUNTRYMEADOW</name>
   <tag></tag>
   <elementGuidId>cbe72705-f612-4d05-baef-0e4634de74f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-2046-3 > span.vscomp-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-2046-3']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf97f787-df6a-4c72-8ad8-65732022047a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-option-text</value>
      <webElementGuid>769af9c7-1e85-42fc-9a5f-3240fb7791f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>COUNTRYMEADOW</value>
      <webElementGuid>f3ce5b92-6a6f-464c-90c7-d1ab200182cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-enter-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>f08e3b5e-a731-4aec-a8d2-fb276d2726a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-z-index</name>
      <type>Main</type>
      <value>251</value>
      <webElementGuid>e8d8a5b1-6d9d-4050-9e12-cb39fa48f258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-font-size</name>
      <type>Main</type>
      <value>14px</value>
      <webElementGuid>efd3b470-b3e6-46f6-8e65-1669ccf89c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-alignment</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>b8a28815-700e-41ba-8f11-f39fb858c0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-max-width</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>e66f6aab-db4b-48c7-b700-e44882bfa5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-ellipsis-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>20201a2b-17d5-4481-92f4-4464a86eb380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-allow-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95c38254-05d4-44d9-a35a-38eb777b5255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            COUNTRYMEADOW
          </value>
      <webElementGuid>965c3d44-e003-42ac-8205-2eff92581410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-2046-3&quot;)/span[@class=&quot;vscomp-option-text&quot;]</value>
      <webElementGuid>75bf4973-8d45-4d0a-89cf-adba03823b19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-2046-3']/span</value>
      <webElementGuid>b681db35-dbf8-456a-891a-e824cd3e1bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARDINAL C2'])[1]/following::span[1]</value>
      <webElementGuid>1eaca458-2d11-4942-b8c9-8e3aa235edde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARDINAL'])[1]/following::span[2]</value>
      <webElementGuid>e8cdbf41-90ad-4852-ae35-efc8a97f2857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COUNTRYMEADOW 2'])[1]/preceding::span[1]</value>
      <webElementGuid>8ebe34f1-0c0c-4623-9df5-003ed2f5e823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D7- Asiongan 2'])[1]/preceding::span[2]</value>
      <webElementGuid>060e402c-70de-4b3b-91d6-6c34b83d4486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COUNTRYMEADOW']/parent::*</value>
      <webElementGuid>1e313027-7c2a-4a25-88ee-c62cbf2420f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div[2]/div/div[4]/span</value>
      <webElementGuid>d6dfab16-391a-4471-8688-658cf1c79cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            COUNTRYMEADOW
          ' or . = '
            COUNTRYMEADOW
          ')]</value>
      <webElementGuid>8f9cb923-6aee-409f-bd9c-c9093edb6af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
