<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stockholder Information_osui-submenu__h_be17fb</name>
   <tag></tag>
   <elementGuidId>537ca2ac-c6e4-494a-b3b3-1cc870170403</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b3-SubMenuHeader > div.osui-submenu__header__icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b3-SubMenuHeader']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c922dafe-fafb-46e6-89ce-4586f297447f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__icon</value>
      <webElementGuid>e0f565f0-05cc-45f5-a5d2-ca37474565d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-SubMenuHeader&quot;)/div[@class=&quot;osui-submenu__header__icon&quot;]</value>
      <webElementGuid>bdaa09be-7223-4be0-baa0-b9a40ab9f378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-SubMenuHeader']/div[2]</value>
      <webElementGuid>3ef80351-3cb8-4a60-9608-e64f82c84794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>37f8fead-7081-46ca-84b9-285c6e8bc8be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
